Repository openshift/operator-framework-olm, pull requests merged in 2021-08, with the labels that each got.

#148 Bug 1985125: fix(og): Fix missing MultiOperatorGroups condition in some cases (#2305)
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#147 Bug 1989600: Registry server RSS and CPU utilization too high during normal operation
  staging/operator-registry/cmd/opm/registry/serve.go
  staging/operator-registry/cmd/registry-server/main.go
  staging/operator-registry/pkg/registry/empty.go
  staging/operator-registry/pkg/registry/interface.go
  staging/operator-registry/pkg/registry/query.go
  staging/operator-registry/pkg/registry/query_test.go
  staging/operator-registry/pkg/server/server.go
  staging/operator-registry/pkg/sqlite/query.go
  staging/operator-registry/pkg/sqlite/query_sql_test.go
  staging/operator-registry/pkg/sqlite/query_test.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/registry/serve.go
  vendor/github.com/operator-framework/operator-registry/cmd/registry-server/main.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/empty.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/query.go
  vendor/github.com/operator-framework/operator-registry/pkg/server/server.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#149 Bug 1989710: Prune unused ClusterServiceVersion fields from catalog's informer.
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/lib/index/api.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/index/api.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#151 Bug 1954869: Add PriorityClass setting to registry pods for default CatalogSource (#2304)
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#154 Bug 1989704: fix(openshift): block upgrades on invalid max properties (#2302)
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#134 Bug 1986023: Translate legacy "bundle dependencies" to properties.
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#136 Bug 1985697: Update the package-server-manager leader election configuration
  cmd/package-server-manager/main.go
  cmd/package-server-manager/util.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm

#159 Bug 1990850: Handle property and dependency values of type BLOB in ListBundles.
  staging/operator-registry/pkg/sqlite/query.go
  staging/operator-registry/pkg/sqlite/query_sql_test.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm

#155 Bug 1989711: fix(openshift): block upgrades on invalid max properties (#2302)
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm, cherry-pick-approved

#144 Bug 1991662: Catalog switcher
  go.mod
  go.sum
  staging/operator-lifecycle-manager/cmd/catalog/main.go
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-catalogsources.crd.yaml
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  staging/operator-lifecycle-manager/pkg/lib/catalogsource/catalogsource_update.go
  staging/operator-lifecycle-manager/pkg/lib/catalogsource/image_template.go
  staging/operator-lifecycle-manager/pkg/lib/catalogsource/image_template_test.go
  staging/operator-lifecycle-manager/scripts/copy_crds.sh
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  vendor/github.com/distribution/distribution/LICENSE
  vendor/github.com/distribution/distribution/reference/helpers.go
  vendor/github.com/distribution/distribution/reference/normalize.go
  vendor/github.com/distribution/distribution/reference/reference.go
  vendor/github.com/distribution/distribution/reference/regexp.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/catalog/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/catalogsource/catalogsource_update.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/catalogsource/image_template.go
  vendor/k8s.io/apimachinery/pkg/util/version/doc.go
  vendor/k8s.io/apimachinery/pkg/util/version/version.go
  vendor/modules.txt
Labels: approved, lgtm

#160 Bug 1983673: Check for pruned bundles on add in replaces mode
  staging/operator-registry/cmd/opm/index/add.go
  staging/operator-registry/pkg/lib/registry/registry.go
  staging/operator-registry/pkg/lib/registry/registry_test.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/index/add.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/registry/registry.go
Labels: approved, lgtm

#161 Bug 1989460: chore(opm): note that whole dependency packages are added to the diff for now
  staging/operator-registry/cmd/opm/alpha/diff/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low

#163 Bug 1989796: docs(diff): add point about versions that differ
  staging/operator-registry/cmd/opm/alpha/diff/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low

#166 Bug 1993286: fix(openshift): drop z from next calculated y-stream (#2324)
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm

#164 Bug 1989431: fix(opm): clarify that bundle declcfgs are not valid refs alone
  staging/operator-registry/cmd/opm/alpha/diff/cmd.go
  staging/operator-registry/internal/action/diff.go
  staging/operator-registry/internal/action/diff_test.go
  staging/operator-registry/internal/action/list.go
  staging/operator-registry/internal/action/render.go
  staging/operator-registry/internal/action/render_test.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go
  vendor/github.com/operator-framework/operator-registry/internal/action/diff.go
  vendor/github.com/operator-framework/operator-registry/internal/action/list.go
  vendor/github.com/operator-framework/operator-registry/internal/action/render.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low

#167 Bug 1994110: fix(openshift): drop z from next calculated y-stream
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm

#138 chore(ci): add verify-commits make target
  Makefile
  scripts/verify_commits.sh
Labels: approved, lgtm

#169 Bug 1992677: validate maxocpversion to have major.minor format
  staging/api/pkg/validation/internal/community.go
  staging/api/pkg/validation/internal/community_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/community.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent, qe-approved

#171 Bug 1996139: chore(verify-commits): initialize variable
  scripts/verify_commits.sh
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm

#150 Bug 1943284: Fix nil function in buildContext return values
  staging/operator-registry/pkg/lib/indexer/indexer.go
  staging/operator-registry/pkg/lib/indexer/indexer_test.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/indexer/indexer.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm

#172 Bug 1996306: Update kubebuilder installation in the build root dockerfile
  base.Dockerfile
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm

#174 Bug 1994038: Update kubebuilder installation in the build root dockerfile
  base.Dockerfile
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, bugzilla/severity-urgent

#173 [release-4.8] Bug 1994038: clarify maxOpenShiftVersion upgrade error message
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, bugzilla/severity-urgent

#157 Bug 1932139: Ensure cross-compiled opm binaries produce non-empty version information
  Makefile
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm

#175 Bug 1995300: opm validate: check for cycles and stranded bundles in channel validation
  staging/operator-registry/internal/model/model.go
  staging/operator-registry/internal/model/model_test.go
  vendor/github.com/operator-framework/operator-registry/internal/model/model.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm

#137 Bug 1978340: Ensure the PackageServer CSV contains a hard pod anti-affinity configuration
  manifests/0000_50_olm_00-packageserver.pdb.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  pkg/manifests/csv.yaml
  pkg/package-server-manager/config.go
  pkg/package-server-manager/controller_test.go
  scripts/generate_crds_manifests.sh
  scripts/packageserver-deployment.patch.yaml
  scripts/packageserver-pdb.yaml
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm

#178 Bug 1999159: Update OWNERS file
  OWNERS
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm
