Repository openshift/operator-framework-olm, pull requests merged in 2021-07, with the labels that each got.

#108 Bug 1977479: fix configmap registry server liveness probe timeouts
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#117 [release-4.8] Bug 1982252: remove cleanup from startup
  staging/operator-lifecycle-manager/cmd/olm/cleanup.go
  staging/operator-lifecycle-manager/cmd/olm/cleanup_test.go
  staging/operator-lifecycle-manager/cmd/olm/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/cleanup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/main.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#119 Bug 1982250: (fix)InstallPlan: Do not tranisition IP to failed on OG/SA failure
  staging/operator-lifecycle-manager/doc/design/architecture.md
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#99 Migrate the PackageServer CSV management to a secondary controller
  Makefile
  cmd/package-server-manager/main.go
  cmd/package-server-manager/start.go
  go.mod
  go.sum
  manifests/0000_50_olm-06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm-06-psm-operator.deployment.yaml
  operator-lifecycle-manager.Dockerfile
  pkg/manifests/csv.yaml
  pkg/manifests/manifests.go
  pkg/package-server-manager/config.go
  pkg/package-server-manager/controller.go
  pkg/package-server-manager/controller_test.go
  scripts/generate_crds_manifests.sh
  scripts/packageserver-deployment.patch.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#112 Implement Continuous Profiling
  Makefile
  cmd/collect-profiles/main.go
  cmd/collect-profiles/profiling_test.go
  go.mod
  manifests/0000_50_olm-06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm-06-psm-operator.deployment.yaml
  manifests/0000_50_olm_00-pprof-config.yaml
  manifests/0000_50_olm_00-pprof-rbac.yaml
  manifests/0000_50_olm_00-pprof-secret.yaml
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  operator-lifecycle-manager.Dockerfile
  pkg/profiling/config/config.go
  scripts/catalog-deployment.patch.yaml
  scripts/generate_crds_manifests.sh
  scripts/olm-deployment.patch.yaml
  values.yaml
  vendor/modules.txt
Labels: approved, lgtm

#131 Upstream Sync
  go.mod
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/predicates.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/predicates_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-registry/cmd/opm/alpha/cmd.go
  staging/operator-registry/cmd/opm/alpha/generate/cmd.go
  staging/operator-registry/internal/action/generate_dockerfile.go
  staging/operator-registry/internal/action/generate_dockerfile_test.go
  staging/operator-registry/internal/action/render.go
  staging/operator-registry/pkg/containertools/dockerfilegenerator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/predicates.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/generate/cmd.go
  vendor/github.com/operator-framework/operator-registry/internal/action/generate_dockerfile.go
  vendor/github.com/operator-framework/operator-registry/internal/action/render.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/dockerfilegenerator.go
  vendor/modules.txt
Labels: approved, lgtm

#118 [release-4.8] Bug 1982294: Fix for resolution error on channels with deprecated inner entries.
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#130 BUG 1984538: Remove monitoring label from openshift-operators namespace
  manifests/0000_50_olm_00-namespace.yaml
  scripts/generate_crds_manifests.sh
  scripts/monitoring-namespace.patch.yaml
  scripts/namespaces.patch.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#135 Bug 1969902: resolver: remove legacy support for fallback parsing of CSVs
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#120 Bug 1979525: OLM blocks minor OpenShift upgrades when incompatible optional operators are installed
  go.mod
  go.sum
  staging/operator-lifecycle-manager/cmd/olm/main.go
  staging/operator-lifecycle-manager/cmd/olm/manager.go
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/suite_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/synctracker.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/synctracker_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/suite_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/projection/properties_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/manager.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/synctracker.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/flags.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/inject/inject.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#139 Bug 1986685: Fix panic in opm alpha diff when accessing the --skip-tls flag
  staging/operator-registry/cmd/opm/alpha/diff/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#142 Bug 1987160: fix(diff): heads-only mode should not attempt to parse old refs
  staging/operator-registry/cmd/opm/alpha/diff/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#143 Bug 1923111: installplans: retry crd updates on conflicts
  staging/operator-lifecycle-manager/pkg/controller/install/webhook.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/webhook.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
