Repository openshift/operator-framework-olm, pull requests merged in 2021-09, with the labels that each got.

#181 Bug 2000146: Introduce olm.channel schema, remove channel metadata-related bundle properties
  staging/operator-registry/internal/action/list.go
  staging/operator-registry/internal/action/render.go
  staging/operator-registry/internal/action/render_test.go
  staging/operator-registry/internal/action/testdata/foo-index-v0.2.0-declcfg/foo/index.yaml
  staging/operator-registry/internal/action/testdata/index-declcfgs/exp-headsonly/index.yaml
  staging/operator-registry/internal/action/testdata/index-declcfgs/exp-latest/index.yaml
  staging/operator-registry/internal/action/testdata/index-declcfgs/latest/index.yaml
  staging/operator-registry/internal/action/testdata/index-declcfgs/old/index.yaml
  staging/operator-registry/internal/action/testdata/list-index/bar/index.yaml
  staging/operator-registry/internal/action/testdata/list-index/foo/index.yaml
  staging/operator-registry/internal/declcfg/declcfg.go
  staging/operator-registry/internal/declcfg/declcfg_to_model.go
  staging/operator-registry/internal/declcfg/declcfg_to_model_test.go
  staging/operator-registry/internal/declcfg/diff_test.go
  staging/operator-registry/internal/declcfg/helpers_test.go
  staging/operator-registry/internal/declcfg/load.go
  staging/operator-registry/internal/declcfg/model_to_declcfg.go
  staging/operator-registry/internal/declcfg/model_to_declcfg_test.go
  staging/operator-registry/internal/declcfg/properties.go
  staging/operator-registry/internal/declcfg/properties_test.go
  staging/operator-registry/internal/declcfg/write.go
  staging/operator-registry/internal/declcfg/write_test.go
  staging/operator-registry/internal/model/model.go
  staging/operator-registry/internal/model/model_test.go
  staging/operator-registry/internal/property/property.go
  staging/operator-registry/internal/property/property_test.go
  staging/operator-registry/internal/property/scheme.go
  staging/operator-registry/pkg/api/api_to_model.go
  staging/operator-registry/pkg/api/conversion_test.go
  staging/operator-registry/pkg/api/model_to_api.go
  staging/operator-registry/pkg/registry/query_test.go
  staging/operator-registry/pkg/registry/registry_to_model.go
  staging/operator-registry/pkg/registry/registry_to_model_test.go
  staging/operator-registry/pkg/server/server_test.go
  staging/operator-registry/pkg/sqlite/conversion.go
  vendor/github.com/operator-framework/operator-registry/internal/action/list.go
  vendor/github.com/operator-framework/operator-registry/internal/action/render.go
  vendor/github.com/operator-framework/operator-registry/internal/action/testdata/foo-index-v0.2.0-declcfg/foo/index.yaml
  vendor/github.com/operator-framework/operator-registry/internal/action/testdata/index-declcfgs/exp-headsonly/index.yaml
  vendor/github.com/operator-framework/operator-registry/internal/action/testdata/index-declcfgs/exp-latest/index.yaml
  vendor/github.com/operator-framework/operator-registry/internal/action/testdata/index-declcfgs/latest/index.yaml
  vendor/github.com/operator-framework/operator-registry/internal/action/testdata/index-declcfgs/old/index.yaml
  vendor/github.com/operator-framework/operator-registry/internal/declcfg/declcfg.go
  vendor/github.com/operator-framework/operator-registry/internal/declcfg/declcfg_to_model.go
  vendor/github.com/operator-framework/operator-registry/internal/declcfg/load.go
  vendor/github.com/operator-framework/operator-registry/internal/declcfg/model_to_declcfg.go
  vendor/github.com/operator-framework/operator-registry/internal/declcfg/properties.go
  vendor/github.com/operator-framework/operator-registry/internal/declcfg/write.go
  vendor/github.com/operator-framework/operator-registry/internal/model/model.go
  vendor/github.com/operator-framework/operator-registry/internal/property/property.go
  vendor/github.com/operator-framework/operator-registry/internal/property/scheme.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/api_to_model.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/model_to_api.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/conversion.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#179 Bug 2000144: Mark GetBundleForChannel as deprecated and trim its response.
  staging/operator-registry/pkg/api/registry.proto
  staging/operator-registry/pkg/registry/interface.go
  staging/operator-registry/pkg/registry/populator_test.go
  staging/operator-registry/pkg/server/server_test.go
  staging/operator-registry/pkg/sqlite/configmap_test.go
  staging/operator-registry/pkg/sqlite/directory_test.go
  staging/operator-registry/pkg/sqlite/query.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.proto
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm

#140 [release-4.8] Bug 1986476: resolver: remove legacy support for fallback parsing of CSVs
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm, cherry-pick-approved, qe-approved

#185 scripts: Update the README.md to point to the downstream gdoc
  scripts/README.md
Labels: approved, lgtm
