Repository openshift/operator-framework-olm, pull requests merged in 2021-06, with the labels that each got.

#84 Bug 1881522: packageserver CSV: add missing properties
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#86 Bug 1965334: drop xattrs during unpack
  staging/operator-registry/pkg/image/containerdregistry/registry.go
  vendor/github.com/operator-framework/operator-registry/pkg/image/containerdregistry/registry.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#88 Bug 1968700: Fix nil pointer dereference while reporting bundle unpack status.
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#90 Bug 1950047: Fix Template Annotations on Webhooks/API Service CSVs
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/install/certresources_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#100 OWNERS: Add additional reviewers
  OWNERS
Labels: approved, lgtm

#103 Bug 1975824: Resolve InstallPlanStepAppliedWithWarnings alert after some time.
  manifests/0000_90_olm_01-prometheus-rule.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#102 Bug 1975432: Resolve InstallPlanStepAppliedWithWarnings alert after some time.
  manifests/0000_90_olm_01-prometheus-rule.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#95 Makefile,scripts: Introduce additional verification checks
  Makefile
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  scripts/check-staging-vendor.sh
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm

#106 Bug 1976326: fix configmap registry server liveness probe timeouts
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#109 Remove the doc/install directory
  doc/install/local-values.yaml
Labels: approved, lgtm
