Repository openshift/operator-framework-olm, pull requests merged in 2021-05, with the labels that each got.

#68 Bug 1945443: Use DeploymentAvailable instead of custom test for CSV status.
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.deployment-spec.yaml
  staging/operator-lifecycle-manager/deploy/chart/values.yaml
  staging/operator-lifecycle-manager/deploy/ocp/values.yaml
  staging/operator-lifecycle-manager/deploy/upstream/values.yaml
  staging/operator-lifecycle-manager/pkg/controller/install/deployment_test.go
  staging/operator-lifecycle-manager/pkg/controller/install/status_viewer.go
  staging/operator-lifecycle-manager/pkg/controller/install/status_viewer_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/status_viewer.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#71 Bug 1957386: Move config serve and validate to opm alpha
  staging/operator-registry/cmd/opm/alpha/cmd.go
  staging/operator-registry/cmd/opm/alpha/serve/serve.go
  staging/operator-registry/cmd/opm/alpha/validate/validate.go
  staging/operator-registry/cmd/opm/root/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/serve/serve.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/validate/validate.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/root/cmd.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#70 Bug 1956611: Fix CR validation bug on go 1.16
  go.mod
  go.sum
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/hivebug/cr.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/hivebug/crd.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/hivebug/fail.yaml
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/k8s.io/kube-openapi/pkg/schemaconv/smd.go
  vendor/k8s.io/kube-openapi/pkg/util/util.go
  vendor/k8s.io/kube-openapi/pkg/validation/validate/type.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#72 Bug 1955761: Set reason/message for Available condition in packageserver co
  staging/operator-lifecycle-manager/pkg/lib/operatorstatus/builder.go
  staging/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter.go
  staging/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter_test.go
  staging/operator-lifecycle-manager/pkg/lib/operatorstatus/monitor.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/builder.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/monitor.go
Labels: approved, lgtm

#77 Bug 1953977: Add tolerant delegating auth config for PackageServer
  staging/operator-lifecycle-manager/pkg/package-server/server/server.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/server/server.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#78 Bug 1921264: Fail InstallPlan on bundle unpack timeout
  staging/operator-lifecycle-manager/cmd/catalog/main.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundlefakes/fake_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/catalog/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#76 Bug 1958285: Simplify deployment status check to reduce flapping.
  staging/operator-lifecycle-manager/pkg/controller/install/status_viewer.go
  staging/operator-lifecycle-manager/pkg/controller/install/status_viewer_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/status_viewer.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#67 Bug 1951387: Add after deprecation
  staging/operator-registry/pkg/registry/populator_test.go
  staging/operator-registry/pkg/sqlite/load.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#79 Bug 1961314: fix race in test with mockRepo/mockBlobStore
  staging/operator-registry/pkg/image/registry_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#80 Bug 1961320: feat(metrics): Emit metrics for CatalogSource state
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/metrics/metrics.go
  staging/operator-lifecycle-manager/test/e2e/like_metric_matcher_test.go
  staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#81 Bug 1959158: Make ClusterOperator Available condition sticky.
  staging/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter.go
  staging/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#82 Bug 1961472: Explicitly set `readOnlyRootFilesystem: false` on created registry pods.
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#83 Bug 1945548: Filter secret names for registry pod's sa
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
