Repository openshift/operator-framework-olm, pull requests merged in 2021-04, with the labels that each got.

#35 Bug 1945584: Remove overrides for GOOS and GOARCH in cpb Makefile recipe.
  Makefile
  operator-lifecycle-manager.Dockerfile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#39 staging/olm: Re-generate test fake package(s)
  staging/operator-lifecycle-manager/pkg/fakes/fake_registry_store.go
Labels: approved, lgtm

#40 Bug 1913525: Bump the k8s dependencies to v0.20.4
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authorization.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#44 Bug 1946838: Do not adopt copied CSVs
  staging/operator-lifecycle-manager/pkg/controller/operators/adoption_controller.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/operatorcondition_controller_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/adoption_controller.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#46 Update the staging/operator-lifecycle-manager tree
  go.mod
  go.sum
  staging/operator-lifecycle-manager/doc/design/architecture.md
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
  staging/operator-lifecycle-manager/pkg/lib/scoped/error.go
  staging/operator-lifecycle-manager/pkg/lib/scoped/querier.go
  staging/operator-lifecycle-manager/pkg/lib/scoped/querier_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/scoped/error.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/scoped/querier.go
  vendor/modules.txt
Labels: approved, lgtm

#49 [sync] Staged api to 01e8bf8b (v0.8.0) and olm to c480add3.
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-operators.crd.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-services.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_13-operatorgroup-default.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  manifests/0000_90_olm_00-service-monitor.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  scripts/tracked
  staging/api/.github/workflows/go.yaml
  staging/api/crds/operators.coreos.com_clusterserviceversions.yaml
  staging/api/crds/operators.coreos.com_installplans.yaml
  staging/api/crds/zz_defs.go
  staging/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  staging/api/pkg/operators/v1alpha1/installplan_types.go
  staging/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  staging/api/pkg/validation/internal/operatorhub.go
  staging/api/pkg/validation/internal/operatorhub_test.go
  staging/api/pkg/validation/internal/testdata/valid_bundle_v1beta1/etcdbackups.etcd.database.coreos.com.crd.yaml
  staging/api/pkg/validation/internal/testdata/valid_bundle_v1beta1/etcdclusters.etcd.database.coreos.com.crd.yaml
  staging/api/pkg/validation/internal/testdata/valid_bundle_v1beta1/etcdoperator.v0.9.4.clusterserviceversion.yaml
  staging/api/pkg/validation/internal/testdata/valid_bundle_v1beta1/etcdrestores.etcd.database.coreos.com.crd.yaml
  staging/operator-lifecycle-manager/cmd/catalog/main.go
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-installplans.crd.yaml
  staging/operator-lifecycle-manager/deploy/ocp/values.yaml
  staging/operator-lifecycle-manager/deploy/upstream/quickstart/crds.yaml
  staging/operator-lifecycle-manager/deploy/upstream/quickstart/install.sh
  staging/operator-lifecycle-manager/deploy/upstream/values.yaml
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  staging/operator-lifecycle-manager/manifests/0000_50_olm_00-installplans.crd.yaml
  staging/operator-lifecycle-manager/manifests/0000_90_olm_01-prometheus-rule.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go
  staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_installplans.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/catalog/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go
Labels: approved, lgtm

#47 staging/operator-registry: Pull in all non-opm-add declarative config updates
  staging/operator-registry/Makefile
  staging/operator-registry/cmd/opm/root/cmd.go
  staging/operator-registry/cmd/opm/validate/validate.go
  staging/operator-registry/internal/declcfg/declcfg_to_model.go
  staging/operator-registry/internal/declcfg/declcfg_to_model_test.go
  staging/operator-registry/internal/declcfg/helpers_test.go
  staging/operator-registry/internal/model/model.go
  staging/operator-registry/internal/model/model_test.go
  staging/operator-registry/operator-registry.Dockerfile
  staging/operator-registry/pkg/api/api_to_model.go
  staging/operator-registry/pkg/api/conversion_test.go
  staging/operator-registry/pkg/api/model_to_api.go
  staging/operator-registry/pkg/lib/config/validate.go
  staging/operator-registry/pkg/registry/query_test.go
  staging/operator-registry/pkg/registry/testdata/validDeclCfg/cockroachdb.json
  staging/operator-registry/pkg/registry/testdata/validDeclCfg/etcd.json
  staging/operator-registry/pkg/sqlite/conversion_test.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/root/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/validate/validate.go
  vendor/github.com/operator-framework/operator-registry/internal/declcfg/declcfg_to_model.go
  vendor/github.com/operator-framework/operator-registry/internal/model/model.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/api_to_model.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/model_to_api.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/config/validate.go
  vendor/modules.txt
Labels: approved, lgtm

#51 Bug 1948771: Revert "set packageserver replicas to 1 for single node"
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  staging/operator-lifecycle-manager/deploy/chart/values.yaml
  staging/operator-lifecycle-manager/deploy/ocp/values.yaml
  staging/operator-lifecycle-manager/deploy/upstream/quickstart/olm.yaml
  staging/operator-lifecycle-manager/deploy/upstream/values.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#41 Bug 1934080: Preserve existing ServiceAccount owner references during installs.
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/step_ensurer.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/step_ensurer_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/step_ensurer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#50 Bug 1948725: Add IBM managed cloud profile annotations to manifests
  OLM_VERSION
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-operators.crd.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-services.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_13-operatorgroup-default.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  manifests/0000_90_olm_00-service-monitor.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#53 Bug 1949294: fix environment variable merging from subscription.config
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/inject/inject.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/inject/inject_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/inject/inject.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#55 Bug 1938492: Add resource requests for bundle unpacker
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#42 Add management workload annotations
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_00-namespace.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.clusterserviceversion.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.deployment-spec.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#60 Bug 1942522: Fix resolution error if inner entry doesn't provide a required API.
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/util_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#63 Bug 1951652: Retry failures when pulling images
  staging/operator-registry/go.mod
  staging/operator-registry/pkg/image/buildahregistry/_registry.go
  staging/operator-registry/pkg/image/containerdregistry/registry.go
  staging/operator-registry/pkg/image/registry_test.go
  staging/operator-registry/pkg/lib/image/registry.go
  vendor/github.com/operator-framework/operator-registry/pkg/image/containerdregistry/registry.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#64 Add verify target to Makefile.
  Makefile
Labels: approved, lgtm

#62 Bug 1934071: fix(catalog): Reduce namespace resync in resolution failure
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#65 Bug 1952238: Report catalog pod termination logs to catalog operator on exit
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#61 Rename workload annotations
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.clusterserviceversion.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.deployment-spec.yaml
Labels: approved, bugzilla/valid-bug, lgtm
