Repository openshift/operator-framework-olm, pull requests merged in 2022-08, with the labels that each got.

#346 Bug 2097557: use env var for OCP version instead of clusterversion status
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm

#326 Support Global Operators in Console
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_15-csv-viewer.rbac.yaml
  scripts/generate_crds_manifests.sh
  scripts/olm-deployment.patch.yaml
  staging/operator-lifecycle-manager/cmd/olm/main.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/test/e2e/disabling_copied_csv_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, lgtm

#351 Add a more robust script for automating the upstream/downstream sync process
  Makefile
  scripts/common.sh
  scripts/sync.sh
  scripts/sync_pop_candidate.sh
  scripts/verify_commits.sh
Labels: approved, lgtm

#349 Psa downstream
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  pkg/manifests/csv.yaml
  scripts/catalog-deployment.patch.yaml
  scripts/generate_crds_manifests.sh
  scripts/olm-deployment.patch.yaml
  scripts/packageserver-deployment.patch.yaml
  staging/operator-lifecycle-manager/Dockerfile
  staging/operator-lifecycle-manager/Dockerfile.goreleaser
  staging/operator-lifecycle-manager/cmd/catalog/main.go
  staging/operator-lifecycle-manager/cmd/catalog/start.go
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_00-namespace.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.deployment-spec.yaml
  staging/operator-lifecycle-manager/deploy/chart/values.yaml
  staging/operator-lifecycle-manager/deploy/upstream/values.yaml
  staging/operator-lifecycle-manager/e2e.Dockerfile
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  values.yaml
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/catalog/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/catalog/start.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: approved, lgtm

#365 noqe: Update magic catalog for psa changes (#2842)
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog.go
  staging/operator-lifecycle-manager/test/e2e/skopeo.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
Labels: approved, lgtm

#348 Bug 2115874: fix(grpc): Add startupProbe to check for grpc health readiness (#2791)
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed

#362 noqe: operator-registry QoL improvements
  staging/operator-registry/.github/workflows/retest.yaml
  staging/operator-registry/Makefile
  staging/operator-registry/alpha/action/migrate_test.go
  staging/operator-registry/alpha/action/render_test.go
  staging/operator-registry/alpha/property/property_test.go
  staging/operator-registry/pkg/image/mock_test.go
  staging/operator-registry/pkg/lib/bundle/generate_test.go
  staging/operator-registry/pkg/lib/registry/registry_test.go
  staging/operator-registry/pkg/registry/populator_test.go
  staging/operator-registry/pkg/sqlite/conversion_test.go
  staging/operator-registry/pkg/sqlite/directory_test.go
  staging/operator-registry/scripts/fetch
Labels: approved, lgtm

#367 (psa) restrict olm namespace + remove labels from openshift-operators ns
  manifests/0000_50_olm_00-namespace.yaml
  scripts/generate_crds_manifests.sh
  values.yaml
Labels: approved, lgtm

#369 noqe: script fixes
  scripts/crc-deploy.sh
  scripts/sync_pop_candidate.sh
Labels: approved, lgtm

#360 OCPBUGS-78: Cleanup conversion webhooks when an operator is uninstalled
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug
