Repository openshift/operator-framework-olm, pull requests merged in 2022-04, with the labels that each got.

#268 Adds CRC deployment automation and CI documentation
  .gitignore
  Makefile
  docs/downstream-ci.md
  docs/local-testing-with-crc.md
  scripts/crc-deploy.sh
  scripts/crc-start.sh
  scripts/generate_crds_manifests.sh
  scripts/sync_get_candidates.sh
  scripts/sync_pop_candidate.sh
Labels: approved, lgtm

#255 Bug 2055861: Replace collect-profile jobs that haven't completed
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  scripts/generate_crds_manifests.sh
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm, qe-approved

#278 sync: Update staging directories 04-05
  staging/api/pkg/manifests/bundleloader.go
  staging/api/pkg/validation/internal/good_practices.go
  staging/api/pkg/validation/internal/good_practices_test.go
  staging/api/pkg/validation/internal/operatorhub.go
  staging/api/pkg/validation/internal/operatorhub_test.go
  staging/api/pkg/validation/internal/testdata/bundle_with_metadata/manifests/cache.example.com_memcacheds.yaml
  staging/api/pkg/validation/internal/testdata/bundle_with_metadata/manifests/memcached-operator.clusterserviceversion.yaml
  staging/api/pkg/validation/internal/testdata/bundle_with_metadata/metadata/annotations.yaml
  staging/operator-lifecycle-manager/.github/workflows/sanity.yaml
  staging/operator-lifecycle-manager/.golangci.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go
  staging/operator-lifecycle-manager/test/e2e/operator_test.go
  staging/operator-registry/.github/workflows/go-apidiff.yaml
  staging/operator-registry/alpha/action/diff.go
  staging/operator-registry/alpha/declcfg/diff.go
  staging/operator-registry/alpha/declcfg/diff_test.go
  staging/operator-registry/cmd/opm/alpha/diff/cmd.go
  vendor/github.com/operator-framework/api/pkg/manifests/bundleloader.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/good_practices.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/diff.go
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/diff.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go
Labels: approved, lgtm

#279 sync update staging directory 04-07
  .gitignore
  scripts/generate_crds_manifests.sh
  scripts/sync_get_candidates.sh
  scripts/sync_pop_candidate.sh
  staging/operator-lifecycle-manager/.github/workflows/e2e-tests.yml
  staging/operator-lifecycle-manager/.github/workflows/flaky-e2e.yml
  staging/operator-lifecycle-manager/.gitignore
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go
  staging/operator-lifecycle-manager/test/e2e/ctx/provisioner_kind.go
  staging/operator-lifecycle-manager/test/e2e/e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/resource_manager_test.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_client.go
  staging/operator-lifecycle-manager/test/e2e/util/resource_queue.go
Labels: approved, lgtm

#272 Bug 2070131: Fix a bug in deletion of webhook service for replacement
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm, cherry-pick-approved, backport-risk-assessed

#285 Sync 04 11
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go
Labels: approved, lgtm

#289 Downstream Sync 04.13
  go.mod
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  staging/api/crds/operators.coreos.com_operatorgroups.yaml
  staging/api/crds/zz_defs.go
  staging/api/pkg/operators/v1/operatorgroup_test.go
  staging/api/pkg/operators/v1/operatorgroup_types.go
  staging/operator-lifecycle-manager/CONTRIBUTING.md
  staging/operator-lifecycle-manager/README.md
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-operatorgroups.crd.yaml
  staging/operator-lifecycle-manager/doc/dev/reporting_flakes.md
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscriptions_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/instrumented_resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/instrumented_resolver_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
  staging/operator-lifecycle-manager/pkg/fakes/fake_resolver.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog_test.go
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/base/example-operator.v0.1.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/base/example-operator.v0.2.0-2.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/base/example-operator.v0.2.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/base/example-operator.v0.3.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/multiple-bad-versions/example-operator.v0.2.1.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/multiple-bad-versions/example-operator.v0.3.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/replaces/example-operator.v0.3.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/skip-range/example-operator.v0.3.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/skips/example-operator.v0.3.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/magiccatalog/fbc_catalog.json
  staging/operator-lifecycle-manager/test/e2e/testdata/magiccatalog/fbc_initial.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/magiccatalog/fbc_updated.yaml
  staging/operator-lifecycle-manager/test/e2e/util.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operatorgroups.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorgroup_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/instrumented_resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  vendor/modules.txt
Labels: approved, lgtm

#290 Identify fail forward in csvSources (#2743)
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscriptions_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/fail_forward.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/instrumented_resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/instrumented_resolver_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_csvs.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_csvs_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
  staging/operator-lifecycle-manager/pkg/fakes/fake_resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/fail_forward.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/instrumented_resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_csvs.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
Labels: approved, lgtm

#292 Sync OLM commits 04/25
  Makefile
  staging/operator-lifecycle-manager/.github/workflows/retest.yml
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/README.md
  staging/operator-lifecycle-manager/logo/README.md
  staging/operator-lifecycle-manager/logo/logo-dark-mode.svg
  staging/operator-lifecycle-manager/logo/logo.png
  staging/operator-lifecycle-manager/logo/logo.svg
  staging/operator-lifecycle-manager/scripts/run_console_local.sh
  staging/operator-lifecycle-manager/test/e2e/collect-ci-artifacts.sh
  staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go
Labels: approved, lgtm

#294 Bug 2074612: Fix GRPC CheckRegistryServer function (#2756)
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm
