Repository openshift/operator-framework-olm, pull requests merged in 2022-11, with the labels that each got.

#401 OCPBUGS-1272: Add pipe support to render-veneer basic command (#1026)
  staging/operator-registry/alpha/declcfg/load.go
  staging/operator-registry/alpha/declcfg/load_test.go
  staging/operator-registry/alpha/veneer/basic/basic.go
  staging/operator-registry/cmd/opm/alpha/veneer/basic.go
  staging/operator-registry/cmd/opm/alpha/veneer/cmd.go
  staging/operator-registry/cmd/opm/alpha/veneer/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/load.go
  vendor/github.com/operator-framework/operator-registry/alpha/veneer/basic/basic.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/basic.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/valid-bug

#389 OCPBUGS-2898: [release-4.10] fix(openshift): use env var instead of clusterversion status (#2817)
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug

#406 OCPBUGS-2556: Order an operator CR's status.Component.Refs array (#2880)
  staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go
  staging/operator-lifecycle-manager/pkg/controller/operators/operator_controller_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/severity-critical, jira/valid-bug

#396 OCPBUGS-1428: fix service account token secret reference (#2862)
  staging/operator-lifecycle-manager/pkg/lib/scoped/token_retriever.go
  staging/operator-lifecycle-manager/pkg/lib/scoped/token_retriever_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/scoped/token_retriever.go
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/valid-bug
