Repository openshift/operator-framework-olm, pull requests merged in 2022-12, with the labels that each got.

#400 provide the capability to filter mermaid output to a single package name / skipRange support (#1023)
  staging/operator-registry/alpha/declcfg/write.go
  staging/operator-registry/alpha/declcfg/write_test.go
  staging/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  staging/operator-registry/cmd/opm/alpha/veneer/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/write.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#394 OCPBUGS-1088: Run collect-profile pod on management nodes
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  scripts/generate_crds_manifests.sh
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/valid-bug

#421 OCPBUGS-4799: Fix label key truncation for subscription annotations (#2731)
  staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#422 Updates to OWNERS file
  OWNERS
Labels: approved, lgtm, docs-approved, qe-approved, px-approved
