Repository openshift/operator-framework-olm, pull requests merged in 2022-03, with the labels that each got.

#257 Update the build root Dockerfile base image
  base.Dockerfile
Labels: approved, lgtm

#258 Fix install_kubebuilder.sh script
  scripts/install_kubebuilder.sh
Labels: approved, lgtm

#245 Bug 1975543: Use CVO to delete manifests removed from OLM
  manifests/0000_50_olm_11-olm-operators.configmap.removed.yaml
  manifests/0000_50_olm_12-olm-operators.catalogsource.removed.yaml
  manifests/0000_50_olm_14-packageserver.subscription.removed.yaml
  scripts/generate_crds_manifests.sh
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low

#262 Remove unsupported project_image from .ci-operator.yaml
  .ci-operator.yaml
Labels: approved, lgtm

#261 Update PATH setting in base Dockerfile
  base.Dockerfile
Labels: approved, lgtm

#270 Makefile: Remove the duplicate unit/psm target
  Makefile
Labels: approved, lgtm

#253 Bug 2054848: Do not modify object from the lister cache (#2562)
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/install/apiservice.go
  staging/operator-lifecycle-manager/pkg/controller/install/webhook.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/apiservice.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/webhook.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed
