Repository openshift/operator-framework-olm, pull requests merged in 2022-09, with the labels that each got.

#371 OCPBUGS-459: fix(grpc): Add startupProbe to check for grpc health readiness (#2791)
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#374 OLM-2726, OCPBUGS-643: downstreaming `opm serve` changes from operator-registry
  staging/operator-registry/alpha/action/generate_dockerfile.go
  staging/operator-registry/alpha/action/generate_dockerfile_test.go
  staging/operator-registry/cmd/opm/registry/serve.go
  staging/operator-registry/cmd/opm/serve/serve.go
  staging/operator-registry/go.mod
  staging/operator-registry/pkg/registry/query.go
  staging/operator-registry/pkg/registry/query_test.go
  staging/operator-registry/pkg/registry/syscall_unix.go
  staging/operator-registry/pkg/registry/syscall_windows.go
  staging/operator-registry/pkg/registry/tar.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/generate_dockerfile.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/registry/serve.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/query.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/syscall_unix.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/syscall_windows.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/tar.go
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/valid-bug

#375 Bug OCPBUGS-828: backport `opm serve` caching functionality (and bugfix) + `opm serve` leaving orphan tmpfiles
  go.mod
  staging/operator-registry/alpha/action/generate_dockerfile.go
  staging/operator-registry/alpha/action/generate_dockerfile_test.go
  staging/operator-registry/cmd/opm/registry/serve.go
  staging/operator-registry/cmd/opm/serve/serve.go
  staging/operator-registry/go.mod
  staging/operator-registry/go.sum
  staging/operator-registry/pkg/registry/query.go
  staging/operator-registry/pkg/registry/query_test.go
  staging/operator-registry/pkg/registry/syscall_unix.go
  staging/operator-registry/pkg/registry/syscall_windows.go
  staging/operator-registry/pkg/registry/tar.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/generate_dockerfile.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/registry/serve.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/query.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/syscall_unix.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/syscall_windows.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/tar.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#376 OLM-2753: Semver veneer pipe support
  staging/operator-registry/alpha/veneer/semver/README.md
  staging/operator-registry/alpha/veneer/semver/semver.go
  staging/operator-registry/cmd/opm/alpha/veneer/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/veneer/semver/README.md
  vendor/github.com/operator-framework/operator-registry/alpha/veneer/semver/semver.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go
Labels: approved, lgtm, qe-approved

#377 OLM-1803 channel upgrade graph visualization
  staging/operator-registry/alpha/declcfg/write.go
  staging/operator-registry/alpha/declcfg/write_test.go
  staging/operator-registry/cmd/opm/alpha/cmd.go
  staging/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  staging/operator-registry/cmd/opm/alpha/veneer/semver.go
  staging/operator-registry/cmd/opm/render/cmd.go
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/write.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/render/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved

#359 OLM-2690: Subscription affinity
  go.mod
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  staging/api/crds/operators.coreos.com_subscriptions.yaml
  staging/api/crds/zz_defs.go
  staging/api/pkg/operators/v1alpha1/subscription_types.go
  staging/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-subscriptions.crd.yaml
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/initializer.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/inject/inject.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/inject/inject_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_subscriptions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/initializer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/inject/inject.go
  vendor/modules.txt
Labels: approved, lgtm, docs-approved

#379 OCPBUGS-650: fixing reliance on candidate channel containing all referenced bundle…
  staging/operator-registry/alpha/veneer/semver/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/veneer/semver/semver.go
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/valid-bug

#378 OCPBUGS-858: Package Server Manager should enforce expected csv values
  go.mod
  pkg/package-server-manager/config.go
  pkg/package-server-manager/controller.go
  pkg/package-server-manager/controller_test.go
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/severity-critical, jira/valid-bug

#380 OCPBUGS-1004: dump descriptive source info on error instead of the source data (#1021)
  staging/operator-registry/cmd/opm/alpha/veneer/semver.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/valid-bug

#370 OLM-2695: Adds downstream only CSV Namespace Labeler Plug-In
  go.mod
  go.sum
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  vendor/github.com/openshift/cluster-policy-controller/LICENSE
  vendor/github.com/openshift/cluster-policy-controller/pkg/psalabelsyncer/nsexemptions/nsexemptions.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved

#382 OCPBUGS-1326: Opm serve cmds
  staging/operator-registry/cmd/opm/serve/serve.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#383 OCPBUGS-122: Psa legacy catalog enablement
  go.mod
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  staging/api/crds/operators.coreos.com_catalogsources.yaml
  staging/api/crds/zz_defs.go
  staging/api/pkg/operators/v1alpha1/catalogsource_types.go
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-catalogsources.crd.yaml
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_catalogsources.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/severity-important, jira/valid-bug

#385 [release-4.10] OCPBUGS-1087: Stop corrupting resolver cache.
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug
