Repository openshift/operator-framework-olm, pull requests merged in 2022-01, with the labels that each got.

#238 Bug 2037168: Remove incorrect cvo annotations
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-olmconfigs.crd.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-operators.crd.yaml
  manifests/0000_50_olm_00-packageserver.pdb.yaml
  manifests/0000_50_olm_00-pprof-config.yaml
  manifests/0000_50_olm_00-pprof-rbac.yaml
  manifests/0000_50_olm_00-pprof-secret.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-olmconfig.yaml
  manifests/0000_50_olm_02-services.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_13-operatorgroup-default.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  manifests/0000_90_olm_00-service-monitor.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  pkg/manifests/csv.yaml
  scripts/generate_crds_manifests.sh
  scripts/packageserver-deployment.patch.yaml
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm

#239 Bug 1952576: Emit CSV metric on startup
  staging/operator-lifecycle-manager/cmd/olm/main.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm

#222 Bug 2030489: Remove oudated subscription update logic to improve resolution delay
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/querier.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/querier_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/querier.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm, cherry-pick-approved, backport-risk-assessed

#242 Bug 2003164: Do not modify object from the lister cache (#2562)
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/install/apiservice.go
  staging/operator-lifecycle-manager/pkg/controller/install/webhook.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/apiservice.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/webhook.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm, qe-approved

#241 Add perdasilva to OWNERS
  OWNERS
Labels: ok-to-test, bugzilla/valid-bug, approved, lgtm

#247 Remove benluddy from approvers.
  OWNERS
Labels: bugzilla/valid-bug, approved, lgtm

#240 Bug 2026343: Address Invalid Address in GRPC Catalogs (#2499)
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm

#248 Bug 2034319: Sync constraint changes
  go.mod
  staging/api/pkg/constraints/constraint.go
  staging/api/pkg/constraints/constraint_test.go
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/predicates.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
  staging/operator-registry/bundles/etcd.0.9.2/metadata/dependencies.yaml
  staging/operator-registry/go.mod
  staging/operator-registry/go.sum
  staging/operator-registry/pkg/registry/populator_test.go
  staging/operator-registry/pkg/registry/registry_to_model.go
  staging/operator-registry/pkg/registry/registry_to_model_test.go
  vendor/github.com/operator-framework/api/pkg/constraints/constraint.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/predicates.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm
