Repository openshift/operator-framework-olm, pull requests merged in 2022-05, with the labels that each got.

#297 Fix currentServiceAccount debug message (#2765)
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: approved, lgtm

#288 [release-4.8] Bug 2074680: Emit CSV metric on startup
  staging/operator-lifecycle-manager/cmd/olm/main.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm, cherry-pick-approved, backport-risk-assessed

#300 Sync 05 03
  staging/operator-lifecycle-manager/.goreleaser.yml
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: approved, lgtm

#299 manifests/*: comply to restricted pod security level
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  pkg/manifests/csv.yaml
  scripts/catalog-deployment.patch.yaml
  scripts/generate_crds_manifests.sh
  scripts/olm-deployment.patch.yaml
  scripts/packageserver-deployment.patch.yaml
Labels: approved, lgtm

#298 [release-4.10] Bug 2080609: Fix GRPC CheckRegistryServer function (#2756)
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm, cherry-pick-approved, backport-risk-assessed

#307 Bug 1982737: Make malformed CSV fail nicely (#2673)
  staging/operator-lifecycle-manager/pkg/controller/errors/errors.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/steps.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/testdata/bad-csv/bad-csv.yaml
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/errors/errors.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/steps.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm

#308 Bug 2039135: add more descriptive error message to pruning of FBC
  staging/operator-registry/fbc-dir/file-based-catalog.Dockerfile
  staging/operator-registry/fbc-dir/file-based-catalog/operator.yaml
  staging/operator-registry/pkg/lib/indexer/indexer.go
  staging/operator-registry/test/e2e/opm_test.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/indexer/indexer.go
Labels: ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm, qe-approved

#306 Bug 2020484: Refactor installer to surface certificate rotation (#2775)
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/install/deployment.go
  staging/operator-lifecycle-manager/pkg/controller/install/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/deployment.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved
