Repository openshift/operator-framework-olm, pull requests merged in 2022-06, with the labels that each got.

#314 Bug 2093288: fix(grpc): Add startupProbe to check for grpc health readiness (#2791)
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm, qe-approved

#309 Bug 2088541: Update catalog source pod security context
  base.Dockerfile
  operator-lifecycle-manager.Dockerfile
  operator-registry.Dockerfile
  staging/operator-lifecycle-manager/Dockerfile
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
  staging/operator-lifecycle-manager/scripts/build_test_images.sh
  staging/operator-lifecycle-manager/test/catalogs/busybox-1.0.0/busybox-dependency/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/busybox-1.0.0/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/busybox-2.0.0/busybox-dependency/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/busybox-2.0.0/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catalog.Dockerfile
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-new/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-new/nginx/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-old/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-old/nginx/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-related/etcd-test/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-related/prometheus/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-related/strimzi-kafka-operator/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/ci-index/kiali/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/single-bundle-index-objects-upgrade-diffname/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/single-bundle-index-objects-upgrade-samename/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/single-bundle-index-objects/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/single-bundle-index-pdb-v1/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/webhook-operator-index-0.0.3/webhook-operator/catalog.json
  staging/operator-lifecycle-manager/test/e2e/collect-ci-artifacts.sh
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/1.0.0/dockerfile
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/1.0.0/manifests/csv.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/1.0.0/manifests/foo.crd.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/1.0.0/metadata/annotations.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/2.0.0/dockerfile
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/2.0.0/manifests/csv.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/2.0.0/manifests/foo.crd.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/2.0.0/metadata/annotations.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/1.0.0/dockerfile
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/1.0.0/manifests/csv.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/1.0.0/metadata/annotations.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/2.0.0/dockerfile
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/2.0.0/manifests/csv.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/2.0.0/metadata/annotations.yaml
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#324 Bug 2100323: Fix legacy registries no longer working (#974)
  Makefile
  operator-lifecycle-manager.Dockerfile
  operator-registry.Dockerfile
  patches/bundle_unpacker_scc.patch
  scripts/crc-deploy.sh
  scripts/e2e.sh
  scripts/unit.sh
  staging/operator-lifecycle-manager/Dockerfile
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
  staging/operator-lifecycle-manager/pkg/controller/security/security.go
  staging/operator-lifecycle-manager/scripts/build_test_images.sh
  staging/operator-lifecycle-manager/test/catalogs/busybox-1.0.0/busybox-dependency/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/busybox-1.0.0/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/busybox-2.0.0/busybox-dependency/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/busybox-2.0.0/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catalog.Dockerfile
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-new/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-new/nginx/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-old/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-old/nginx/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-related/etcd-test/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-related/prometheus/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/catsrc-update-test-related/strimzi-kafka-operator/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/ci-index/kiali/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/single-bundle-index-objects-upgrade-diffname/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/single-bundle-index-objects-upgrade-samename/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/single-bundle-index-objects/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/single-bundle-index-pdb-v1/busybox/catalog.json
  staging/operator-lifecycle-manager/test/catalogs/webhook-operator-index-0.0.3/webhook-operator/catalog.json
  staging/operator-lifecycle-manager/test/e2e/collect-ci-artifacts.sh
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/1.0.0/dockerfile
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/1.0.0/manifests/csv.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/1.0.0/manifests/foo.crd.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/1.0.0/metadata/annotations.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/2.0.0/dockerfile
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/2.0.0/manifests/csv.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/2.0.0/manifests/foo.crd.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox-dependency/2.0.0/metadata/annotations.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/1.0.0/dockerfile
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/1.0.0/manifests/csv.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/1.0.0/metadata/annotations.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/2.0.0/dockerfile
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/2.0.0/manifests/csv.yaml
  staging/operator-lifecycle-manager/test/images/busybox-index/busybox/2.0.0/metadata/annotations.yaml
  staging/operator-registry/pkg/lib/tmp/copy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/security/security.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/tmp/copy.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#320 Bug 2076323: Exclude global catalogs from resolution
  go.mod
  go.sum
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/og_source_provider.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_exclusion_test.go
  staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog_test.go
  staging/operator-lifecycle-manager/test/e2e/util.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_client.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
  staging/operator-lifecycle-manager/test/e2e/util/gomega/assertions.go
  staging/operator-lifecycle-manager/test/e2e/util/gomega/catalogsource_matchers.go
  staging/operator-lifecycle-manager/test/e2e/util/gomega/subscription_matchers.go
  staging/operator-lifecycle-manager/test/e2e/util/test_logging.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/og_source_provider.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, bugzilla/severity-high, approved, lgtm, qe-approved

#327 Bug 2101802: opm bug fix
  staging/operator-registry/pkg/lib/tmp/copy.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/tmp/copy.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium, approved, lgtm, cherry-pick-approved, backport-risk-assessed
