Repository openshift/operator-framework-olm, pull requests merged in 2023-07, with the labels that each got.

#500 OCPBUGS-15737: Re-enable psa plugin
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#502 OCPBUGS-13128: Retry initialization error conditions (#2979)
  staging/operator-lifecycle-manager/pkg/lib/operatorstatus/monitor.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/monitor.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#505 update verification script to work across non-standard bash location
  scripts/verify_commits.sh
Labels: approved, lgtm

#511 Allow cpb to be statically compiled / exempt from FIPS compliance
  operator-lifecycle-manager.Dockerfile
Labels: approved, lgtm

#520 OPRUN-2913: Add DOWNSTREAM_OWNERS
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, jira/valid-reference

#458 OCPBUGS-7904: Cleanup conversion webhooks when an operator is uninstalled
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
