Repository openshift/operator-framework-olm, pull requests merged in 2023-08, with the labels that each got.

#529 OPRUN-3021: Improve README
  README.md
  scripts/README.md
  scripts/sync.sh
  scripts/sync_get_candidates.sh
  scripts/sync_pop_candidate.sh
Labels: approved, lgtm, jira/valid-reference

#527 OCPBUGS-17157: cmd/package-server-manager: add pprof endpoints
  cmd/package-server-manager/main.go
  cmd/package-server-manager/start.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#526 OCPBUGS-17157: operator-registry: cherry-pick to be up-to-date
  go.mod
  staging/operator-registry/.github/workflows/unit.yaml
  staging/operator-registry/cmd/opm/serve/serve.go
  staging/operator-registry/docs/design/bundle-sources.md
  staging/operator-registry/go.mod
  staging/operator-registry/go.sum
  staging/operator-registry/pkg/cache/json.go
  staging/operator-registry/pkg/cache/tar.go
  staging/operator-registry/pkg/cache/tar_test.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/json.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/tar.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#531 OCPBUGS-17157: sync
  go.mod
  go.sum
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  staging/api/.github/workflows/go.yaml
  staging/api/crds/operators.coreos.com_catalogsources.yaml
  staging/api/crds/zz_defs.go
  staging/api/pkg/operators/v1alpha1/catalogsource_types.go
  staging/api/pkg/operators/v1alpha1/clusterserviceversion.go
  staging/api/pkg/operators/v1alpha1/clusterserviceversion_test.go
  staging/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  staging/api/pkg/validation/internal/csv.go
  staging/api/pkg/validation/internal/csv_test.go
  staging/api/pkg/validation/internal/operatorhub.go
  staging/api/pkg/validation/internal/operatorhub_test.go
  staging/api/pkg/validation/internal/testdata/badAnnotationNames.csv.yaml
  staging/api/pkg/validation/internal/testdata/badName.csv.yaml
  staging/api/pkg/validation/internal/testdata/correct.csv.empty.example.yaml
  staging/api/pkg/validation/internal/testdata/correct.csv.olm.properties.annotation.yaml
  staging/api/pkg/validation/internal/testdata/correct.csv.with.conversion.webhook.yaml
  staging/api/pkg/validation/internal/testdata/correct.csv.yaml
  staging/api/pkg/validation/internal/testdata/dataTypeMismatch.csv.yaml
  staging/api/pkg/validation/internal/testdata/invalid.alm-examples.csv.yaml
  staging/api/pkg/validation/internal/testdata/invalid_min_kube_version.csv.yaml
  staging/api/pkg/validation/internal/testdata/noInstallMode.csv.yaml
  staging/operator-lifecycle-manager/OWNERS
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-catalogsources.crd.yaml
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-subscriptions.crd.yaml
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
  staging/operator-registry/.gitignore
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_catalogsources.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#532 Sync 2023 08 04
  staging/operator-lifecycle-manager/cmd/olm/main.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup_test.go
  staging/operator-registry/alpha/template/composite/composite.go
  staging/operator-registry/alpha/template/composite/composite_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/composite/composite.go
  vendor/k8s.io/client-go/metadata/metadatainformer/informer.go
  vendor/k8s.io/client-go/metadata/metadatainformer/interface.go
  vendor/k8s.io/client-go/metadata/metadatalister/interface.go
  vendor/k8s.io/client-go/metadata/metadatalister/lister.go
  vendor/k8s.io/client-go/metadata/metadatalister/shim.go
  vendor/modules.txt
Labels: approved, lgtm

#533 fix the manifests generation
  Makefile
  pkg/manifests/csv.yaml
Labels: approved, lgtm

#535 Add tmshort to owners
  DOWNSTREAM_OWNERS
Labels: approved, lgtm

#537 OPRUN-3022: Add support for make verify to sync script
  Makefile
  scripts/sync_pop_candidate.sh
Labels: approved, lgtm, jira/valid-reference

#538 [4.13] Introduce DOWNSTREAM_OWNERS file
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#539 Add ncdc to DOWNSTREAM_OWNERS
  DOWNSTREAM_OWNERS
Labels: approved, lgtm

#536 [release-4.11] OCPBUGS-16075: fix dynamic conversion webhook
  Makefile
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_exclusion_test.go
  staging/operator-lifecycle-manager/test/e2e/e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#534 OCPBUGS-17157: scripts: add a Go-based bumper, sync upstream
  Makefile
  scripts/README.md
  scripts/bumper/go.mod
  scripts/bumper/go.sum
  scripts/bumper/main.go
  scripts/verify_commits.sh
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#550 scripts/bumper: automate pushing changes and creating PRs
  scripts/bumper/go.mod
  scripts/bumper/go.sum
  scripts/bumper/main.go
Labels: approved, lgtm, jira/valid-bug

#540 OCPBUGS-17791: opm: always serve pprof endpoints, improve server allocations (#1129)
  staging/operator-registry/cmd/opm/serve/serve.go
  staging/operator-registry/pkg/cache/json.go
  staging/operator-registry/pkg/cache/tar.go
  staging/operator-registry/pkg/cache/tar_test.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/json.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/tar.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#546 [release-4.10] OCPBUGS-17779: fix dynamic conversion webhook
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
