Repository openshift/operator-framework-olm, pull requests merged in 2023-10, with the labels that each got.

#579 Sync 2023 10 05 no steve
  go.mod
  manifests/0000_50_olm_00-olmconfigs.crd.yaml
  staging/api/crds/operators.coreos.com_olmconfigs.yaml
  staging/api/crds/zz_defs.go
  staging/api/pkg/operators/v1/olmconfig_test.go
  staging/api/pkg/operators/v1/olmconfig_types.go
  staging/api/pkg/operators/v1/zz_generated.deepcopy.go
  staging/operator-lifecycle-manager/README.md
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-olmconfigs.crd.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.deployment-spec.yaml
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundlefakes/fake_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscriptions_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
  staging/operator-lifecycle-manager/pkg/package-server/server/server.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_exclusion_test.go
  staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/deprecated_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/disabling_copied_csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/dynamic_resource_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/e2e-bare-values.yaml
  staging/operator-lifecycle-manager/test/e2e/e2e-values.yaml
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/fbc_provider.go
  staging/operator-lifecycle-manager/test/e2e/gc_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/packagemanifest_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_olmconfigs.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/olmconfig_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/server/server.go
  vendor/modules.txt
Labels: approved, lgtm

#578 Sync script: handle multi commit merges
  scripts/sync.sh
  scripts/sync_get_candidates.sh
  scripts/sync_pop_candidate.sh
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#593 scripts/bumper: also run `go mod` in nested vendor
  scripts/bumper/main.go
Labels: approved, lgtm

#588 Remove 5m package-server-manager default
  cmd/package-server-manager/main.go
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  pkg/package-server-manager/config.go
  pkg/package-server-manager/controller.go
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm

#565 OCPVE-674: feat: add annotations for capabilities feature
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-olmconfigs.crd.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-operators.crd.yaml
  manifests/0000_50_olm_00-packageserver.pdb.yaml
  manifests/0000_50_olm_00-pprof-config.yaml
  manifests/0000_50_olm_00-pprof-rbac.yaml
  manifests/0000_50_olm_00-pprof-secret.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-olmconfig.yaml
  manifests/0000_50_olm_02-services.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  manifests/0000_50_olm_06-psm-operator.service.yaml
  manifests/0000_50_olm_06-psm-operator.servicemonitor.yaml
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_11-olm-operators.configmap.removed.yaml
  manifests/0000_50_olm_12-olm-operators.catalogsource.removed.yaml
  manifests/0000_50_olm_13-operatorgroup-default.yaml
  manifests/0000_50_olm_14-packageserver.subscription.removed.yaml
  manifests/0000_50_olm_15-csv-viewer.rbac.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  manifests/0000_90_olm_00-service-monitor.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, jira/valid-reference

#592 OCPBUGS-18948: CRD Compatibility Validation
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.cr.fail.v2.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.cr.valid.v1.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.cr.valid.v2.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.old.unserved.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.old.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.unserved.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/single-version-cr.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/single-version-crd.old.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/single-version-crd.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/cr.v2.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/cr.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.no-versions-list.old.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.no-versions-list.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.old.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.unserved.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.yaml
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#595 OCPBUGS-22217: Fixing flake tests so they don't fail 100% of the time.
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#596 OCPBUGS-17408: Do not derive installplan.spec.clusterServiceNames from bundle IDs
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#597 Small sync
  staging/operator-lifecycle-manager/OWNERS
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm

#599 scripts/bumper: only marshal missing commits
  scripts/bumper/main.go
Labels: approved, lgtm

#566 OCPBUGS-19789: Backport OCPBUGS-14698: Rename ClusterRoles created by OperatorGroups [release-4.14]
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
