Repository openshift/operator-framework-olm, pull requests merged in 2023-11, with the labels that each got.

#602 NO-ISSUE: Update downstreaming documentation.
  README.md
  scripts/README.md
Labels: approved, lgtm, jira/valid-reference

#582 OCPBUGS-20400: Add OLMConfig API to control package server sync interval [release-4.14]
  cmd/package-server-manager/main.go
  go.mod
  go.sum
  manifests/0000_50_olm_00-olmconfigs.crd.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  pkg/package-server-manager/config.go
  pkg/package-server-manager/controller.go
  scripts/generate_crds_manifests.sh
  staging/api/crds/operators.coreos.com_olmconfigs.yaml
  staging/api/crds/zz_defs.go
  staging/api/pkg/operators/v1/olmconfig_test.go
  staging/api/pkg/operators/v1/olmconfig_types.go
  staging/api/pkg/operators/v1/zz_generated.deepcopy.go
  staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-olmconfigs.crd.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.deployment-spec.yaml
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/package-server/server/server.go
  staging/operator-lifecycle-manager/test/e2e/e2e-bare-values.yaml
  staging/operator-lifecycle-manager/test/e2e/e2e-values.yaml
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_olmconfigs.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/olmconfig_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/server/server.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#556 OCPBUGS-17041: Release Leader Election on Manager Exit
  cmd/package-server-manager/main.go
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#604 OPRUN-3063: Generate OLM microshift manifests
  microshift-manifests/0000_50_olm_00-catalogsources.crd.yaml
  microshift-manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  microshift-manifests/0000_50_olm_00-installplans.crd.yaml
  microshift-manifests/0000_50_olm_00-namespace.yaml
  microshift-manifests/0000_50_olm_00-olmconfigs.crd.yaml
  microshift-manifests/0000_50_olm_00-operatorconditions.crd.yaml
  microshift-manifests/0000_50_olm_00-operatorgroups.crd.yaml
  microshift-manifests/0000_50_olm_00-operators.crd.yaml
  microshift-manifests/0000_50_olm_00-packageserver.pdb.yaml
  microshift-manifests/0000_50_olm_00-pprof-config.yaml
  microshift-manifests/0000_50_olm_00-pprof-rbac.yaml
  microshift-manifests/0000_50_olm_00-pprof-secret.yaml
  microshift-manifests/0000_50_olm_00-subscriptions.crd.yaml
  microshift-manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  microshift-manifests/0000_50_olm_02-olmconfig.yaml
  microshift-manifests/0000_50_olm_02-services.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.service.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.servicemonitor.yaml
  microshift-manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  microshift-manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_07-olm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  microshift-manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  microshift-manifests/0000_50_olm_11-olm-operators.configmap.removed.yaml
  microshift-manifests/0000_50_olm_12-olm-operators.catalogsource.removed.yaml
  microshift-manifests/0000_50_olm_13-operatorgroup-default.yaml
  microshift-manifests/0000_50_olm_14-packageserver.subscription.removed.yaml
  microshift-manifests/0000_50_olm_15-csv-viewer.rbac.yaml
  microshift-manifests/0000_50_olm_99-operatorstatus.yaml
  microshift-manifests/0000_90_olm_00-service-monitor.yaml
  microshift-manifests/0000_90_olm_01-prometheus-rule.yaml
  microshift-manifests/image-references
  microshift-manifests/kustomization.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#614 OCPBUGS-23508: [release-4.14] Use generated namespaces in e2e tests
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_exclusion_test.go
  staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/deprecated_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/disabling_copied_csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/dynamic_resource_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/gc_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/packagemanifest_e2e_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#605 OCPBUGS-18904: [release-4.14] Improve Leader Election Hand Off
  cmd/package-server-manager/main.go
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#610 OPRUN-3063: Microshift manifests: Ignore "*.removed.yaml" files in kustomization.yaml
  microshift-manifests/kustomization.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, jira/valid-reference

#615 OPRUN-3063: Microshift manifests remove collection-profiles cronjob from kustomization
  microshift-manifests/kustomization.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, jira/valid-reference

#613 NO-ISSUE: scripts: remove legacy bumping implementations
  scripts/README.md
  scripts/bumper/.gitignore
  scripts/bumper/Dockerfile
  scripts/bumper/go.mod
  scripts/bumper/go.sum
  scripts/bumper/main.go
  scripts/sync.sh
  scripts/sync_get_candidates.sh
  scripts/sync_pop_candidate.sh
Labels: approved, lgtm, jira/valid-reference

#622 OPRUN-3063: Microshift manifests fixes
  microshift-manifests/0000_50_olm_15-csv-viewer.rbac.yaml
  microshift-manifests/kustomization.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, jira/valid-reference
