Repository openshift/operator-framework-olm, pull requests merged in 2023-03, with the labels that each got.

#463 OPECO-2646: exclude bundles with `olm.deprecated` property when rendering
  staging/operator-registry/pkg/sqlite/conversion.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/conversion.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, jira/valid-reference

#467 fix pop_candidate script
  scripts/sync_pop_candidate.sh
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#461 OPECO-2737: Veneer template rename
  operator-registry.blacklist
  staging/operator-registry/alpha/action/list_test.go
  staging/operator-registry/alpha/declcfg/load.go
  staging/operator-registry/alpha/template/basic/basic.go
  staging/operator-registry/alpha/template/composite/builder.go
  staging/operator-registry/alpha/template/composite/builder_test.go
  staging/operator-registry/alpha/template/composite/composite.go
  staging/operator-registry/alpha/template/composite/composite_test.go
  staging/operator-registry/alpha/template/composite/config.go
  staging/operator-registry/alpha/template/composite/types.go
  staging/operator-registry/alpha/template/semver/README.md
  staging/operator-registry/alpha/template/semver/major-version-demo.gif
  staging/operator-registry/alpha/template/semver/minor-version-demo.gif
  staging/operator-registry/alpha/template/semver/semver.go
  staging/operator-registry/alpha/template/semver/semver_test.go
  staging/operator-registry/alpha/veneer/semver/major-version-demo.gif
  staging/operator-registry/alpha/veneer/semver/minor-version-demo.gif
  staging/operator-registry/cmd/opm/alpha/cmd.go
  staging/operator-registry/cmd/opm/alpha/template/basic.go
  staging/operator-registry/cmd/opm/alpha/template/cmd.go
  staging/operator-registry/cmd/opm/alpha/template/composite.go
  staging/operator-registry/cmd/opm/alpha/template/semver.go
  staging/operator-registry/cmd/opm/root/cmd.go
  staging/operator-registry/opm-example.Dockerfile
  staging/operator-registry/pkg/image/containerdregistry/registry.go
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/load.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/basic/basic.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/composite/builder.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/composite/composite.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/composite/config.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/composite/types.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/README.md
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/major-version-demo.gif
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/minor-version-demo.gif
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/veneer/semver/major-version-demo.gif
  vendor/github.com/operator-framework/operator-registry/alpha/veneer/semver/minor-version-demo.gif
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/basic.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/composite.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/semver.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/root/cmd.go
  vendor/github.com/operator-framework/operator-registry/pkg/image/containerdregistry/registry.go
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, jira/valid-reference

#460 OCPBUGS-7431: Registry Pod Controller Flag
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#476 OCPBUGS-7910: Sort channels in lexicographical order in Packagemanifestst (#2925)
  staging/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  staging/operator-lifecycle-manager/pkg/package-server/provider/registry_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/provider/registry.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#468 OCPBUGS-6016: UpdateStrategy RegistryPoll with nil Interval
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference
