Repository openshift/operator-framework-olm, pull requests merged in 2023-12, with the labels that each got.

#634 OCPBUGS-25339: [CARRY] Fix panic issue when annotations map is nil
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#636 [release-4.15] OCPBUGS-25367: [CARRY] Fix panic issue when annotations map is nil
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#638 NO-ISSUE: Update verified directories for microshift-manifests
  scripts/common.sh
  scripts/verify_commits.sh
Labels: approved, lgtm, jira/valid-reference
