Repository openshift/operator-framework-olm, pull requests merged in 2023-05, with the labels that each got.

#486 OCPBUGS-1684: Optimize certificate generation
  cmd/collect-profiles/main.go
  go.mod
  go.sum
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#488 OCPBUGS-13321: OCPBUGS-1684: Optimize certificate generation
  cmd/collect-profiles/main.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#489 OCPBUGS-13789: downstream y-streams-for-all semver template changes.
  staging/operator-registry/alpha/declcfg/write.go
  staging/operator-registry/alpha/template/semver/README.md
  staging/operator-registry/alpha/template/semver/major-version-demo.gif
  staging/operator-registry/alpha/template/semver/minor-version-demo.gif
  staging/operator-registry/alpha/template/semver/semver.go
  staging/operator-registry/alpha/template/semver/semver_test.go
  staging/operator-registry/alpha/template/semver/types.go
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/write.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/README.md
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/major-version-demo.gif
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/minor-version-demo.gif
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/types.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference
