Repository openshift/operator-framework-olm, pull requests merged in 2023-02, with the labels that each got.

#435 OCPBUGS-6741: refactor FBC caching (#1051)
  staging/operator-registry/cmd/opm/serve/serve.go
  staging/operator-registry/go.mod
  staging/operator-registry/go.sum
  staging/operator-registry/pkg/cache/cache.go
  staging/operator-registry/pkg/cache/cache_test.go
  staging/operator-registry/pkg/cache/json.go
  staging/operator-registry/pkg/cache/json_test.go
  staging/operator-registry/pkg/cache/pkgs.go
  staging/operator-registry/pkg/cache/syscall_unix.go
  staging/operator-registry/pkg/cache/syscall_windows.go
  staging/operator-registry/pkg/cache/tar.go
  staging/operator-registry/pkg/cache/tar_test.go
  staging/operator-registry/pkg/lib/registry/registry_test.go
  staging/operator-registry/pkg/registry/query.go
  staging/operator-registry/pkg/server/server_test.go
  staging/operator-registry/pkg/sqlite/query.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/cache.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/json.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/pkgs.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/syscall_unix.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/syscall_windows.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/tar.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/query.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#438 Thread Safety test for UpdateSubsSyncCounterStorage (#2918)
  staging/operator-lifecycle-manager/pkg/metrics/metrics_test.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#440 [release-4.12] OCPBUGS-6260: Catalog, fatal error: concurrent map read and map write
  staging/operator-lifecycle-manager/pkg/metrics/metrics.go
  staging/operator-lifecycle-manager/pkg/metrics/metrics_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#441 OCPBUGS-7086: cherry-pick pull request refactor FBC caching (#1051) f…
  staging/operator-registry/cmd/opm/serve/serve.go
  staging/operator-registry/go.mod
  staging/operator-registry/go.sum
  staging/operator-registry/pkg/cache/cache.go
  staging/operator-registry/pkg/cache/cache_test.go
  staging/operator-registry/pkg/cache/json.go
  staging/operator-registry/pkg/cache/json_test.go
  staging/operator-registry/pkg/cache/pkgs.go
  staging/operator-registry/pkg/cache/syscall_unix.go
  staging/operator-registry/pkg/cache/syscall_windows.go
  staging/operator-registry/pkg/cache/tar.go
  staging/operator-registry/pkg/cache/tar_test.go
  staging/operator-registry/pkg/lib/registry/registry_test.go
  staging/operator-registry/pkg/registry/query.go
  staging/operator-registry/pkg/server/server_test.go
  staging/operator-registry/pkg/sqlite/query.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/cache.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/json.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/pkgs.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/syscall_unix.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/syscall_windows.go
  vendor/github.com/operator-framework/operator-registry/pkg/cache/tar.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/query.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#444 OCPBUGS-7102: make plugin e2e tests skippable
  Makefile
  go.mod
  go.sum
  scripts/update_plugin_deps.sh
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#446 OCPBUGS-672: Catalog Pod Startup Probe Timeout
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#449 [release-4.12] OCPBUGS-7556: Defuse E2e timebomb
  Makefile
  go.mod
  go.sum
  scripts/update_plugin_deps.sh
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#448 update cpc dep
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#445 OCPBUGS-948: Set openshift.io/scc label to empty
  manifests/0000_50_olm_00-namespace.yaml
  scripts/namespaces.patch.yaml
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#454 OCPBUGS-7769: [release-4.12] update cluster policy operator dependency
  go.mod
  go.sum
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
