Repository openshift/operator-framework-olm, pull requests merged in 2023-01, with the labels that each got.

#425 OCPBUGS-4955: Set ImagePullPolicy of bundle unpacker to "IfNotPresent" for image digests
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/pkg/lib/image/image.go
  staging/operator-lifecycle-manager/pkg/lib/image/image_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/image/image.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/severity-low, jira/valid-bug

#387 [release-4.10] OCPBUGS-1525: Package Server Manager should enforce expected csv values
  go.mod
  go.sum
  pkg/package-server-manager/config.go
  pkg/package-server-manager/controller.go
  pkg/package-server-manager/controller_test.go
  vendor/github.com/cespare/xxhash/v2/.travis.yml
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug

#429 OCPBUGS-5523: Catalog, fatal error: concurrent map read and map write
  staging/operator-lifecycle-manager/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#433 OCPBUGS-6241: Fix art consistency
  .ci-operator.yaml
  operator-lifecycle-manager.Dockerfile
  operator-registry.Dockerfile
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference
