Repository openshift/operator-framework-olm, pull requests merged in 2023-09, with the labels that each got.

#548 OCPBUGS-18305,RHIBMCS-151: Copied csv listing backport
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#555 OCPBUGS-17950: Make packageserver wakeup interval configurable
  cmd/package-server-manager/main.go
  cmd/package-server-manager/start.go
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  pkg/manifests/manifests.go
  pkg/package-server-manager/config.go
  pkg/package-server-manager/controller.go
  pkg/package-server-manager/controller_test.go
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#528 OCPBUGS-15067: Bump Masterminds/vcs to 1.13.3
  go.mod
  go.sum
  vendor/github.com/Masterminds/vcs/.golangci.yml
  vendor/github.com/Masterminds/vcs/.travis.yml
  vendor/github.com/Masterminds/vcs/CHANGELOG.md
  vendor/github.com/Masterminds/vcs/Makefile
  vendor/github.com/Masterminds/vcs/README.md
  vendor/github.com/Masterminds/vcs/appveyor.yml
  vendor/github.com/Masterminds/vcs/bzr.go
  vendor/github.com/Masterminds/vcs/git.go
  vendor/github.com/Masterminds/vcs/git_unix.go
  vendor/github.com/Masterminds/vcs/git_windows.go
  vendor/github.com/Masterminds/vcs/glide.yaml
  vendor/github.com/Masterminds/vcs/hg.go
  vendor/github.com/Masterminds/vcs/svn.go
  vendor/github.com/Masterminds/vcs/vcs_remote_lookup.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#551 OCPBUGS-17157: manifests: add $GOMEMLIMIT to PSM
  cmd/package-server-manager/main.go
  cmd/package-server-manager/start.go
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  manifests/0000_50_olm_06-psm-operator.service.yaml
  manifests/0000_50_olm_06-psm-operator.servicemonitor.yaml
  manifests/image-references
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#569 scripts/bumper: exit when there's nothing to do
  scripts/bumper/main.go
Labels: approved, lgtm
