Repository openshift/operator-framework-olm, pull requests merged in 2024-12, with the labels that each got.

#905 [release-4.14] OCPBUGS-45080: SSA for Services and ClusterRoleBindings
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/install/certresources_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/operatorclientmocks/mock_client.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/service.go
  staging/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/service.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#914 NO-ISSUE: Remove m1kola from owners
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, jira/valid-reference

#918 [release-4.18] OCPBUGS-46474:catalog-operator: Delete Pods that were evicted (#3459)
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#921 OCPBUGS-46595: CRD upgrade existing CR validation fix (#3442)
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/postgrestolerations/crd.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/postgrestolerations/pgadmin.cr.yaml
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
