Repository openshift/operator-framework-olm, pull requests merged in 2024-10, with the labels that each got.

#878 OCPBUGS-42828: add optional schema migrations; default to olm.bundle.object instead of olm.csv.metadata
  staging/operator-registry/alpha/action/migrate.go
  staging/operator-registry/alpha/action/migrate_test.go
  staging/operator-registry/alpha/action/migrations/000_bundle_object_to_csv_metadata.go
  staging/operator-registry/alpha/action/migrations/migrations.go
  staging/operator-registry/alpha/action/migrations/migrations_test.go
  staging/operator-registry/alpha/action/render.go
  staging/operator-registry/alpha/action/render_test.go
  staging/operator-registry/alpha/template/basic/basic.go
  staging/operator-registry/alpha/template/composite/builder.go
  staging/operator-registry/alpha/template/semver/semver.go
  staging/operator-registry/alpha/template/semver/types.go
  staging/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  staging/operator-registry/cmd/opm/alpha/template/basic.go
  staging/operator-registry/cmd/opm/alpha/template/semver.go
  staging/operator-registry/cmd/opm/migrate/cmd.go
  staging/operator-registry/cmd/opm/render/cmd.go
  staging/operator-registry/pkg/api/api_to_model.go
  staging/operator-registry/pkg/api/conversion_test.go
  staging/operator-registry/pkg/registry/registry_to_model.go
  staging/operator-registry/pkg/registry/registry_to_model_test.go
  staging/operator-registry/pkg/server/server_test.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrate.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrations/000_bundle_object_to_csv_metadata.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrations/migrations.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/render.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/basic/basic.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/composite/builder.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/types.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/basic.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/semver.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/migrate/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/render/cmd.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/api_to_model.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#884 OCPBUGS-43581: Fix TLS handshake error
  cmd/collect-profiles/main.go
Labels: approved, lgtm, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#876 NO-ISSUE: [release-4.13] Backport e2e fixes
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/packagemanifest_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/user_defined_sa_test.go
  staging/operator-lifecycle-manager/test/e2e/util.go
  staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#880 NO-ISSUE: [release-4.12] Backport e2e fixes
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/packagemanifest_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/user_defined_sa_test.go
  staging/operator-lifecycle-manager/test/e2e/util.go
  staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#885 [release-4.17] OCPBUGS-43965: Return an error when the IP status cannot be updated
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
