Repository openshift/operator-framework-olm, pull requests merged in 2024-03, with the labels that each got.

#708 OCPBUGS-23744: Wait for required RBAC before creating packageserver CSV
  cmd/package-server-manager/main.go
  pkg/package-server-manager/controller.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#707 [release-4.15] OCPBUGS-30141: ClusterRoleBinding + Service SSA cherry-pick
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/install/certresources_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/operatorclientmocks/mock_client.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/service.go
  staging/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/service.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#704 OCPBUGS-25019: building rhel8/rhel9/static clis in payload image
  operator-framework-cli.Dockerfile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#714 NO-ISSUE: Semver lastedge error (#1169) [sync]
  staging/operator-registry/alpha/template/semver/semver.go
  staging/operator-registry/alpha/template/semver/semver_test.go
  staging/operator-registry/alpha/template/semver/types.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/types.go
Labels: approved, lgtm, jira/valid-reference

#700 OCPBUGS-29553: Apply hypershift cluster-profile for ibm-cloud-managed
  pkg/manifests/csv.yaml
  scripts/packageserver-deployment.patch.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#720 NO-ISSUE: UPSTREAM: <carry>: update owners
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, jira/valid-reference
