Repository openshift/operator-framework-olm, pull requests merged in 2024-09, with the labels that each got.

#851 OCPBUGS-39458: add optional schema migrations; default to olm.bundle.object instead of olm.csv.metadata (#1384)
  staging/operator-registry/alpha/action/migrate.go
  staging/operator-registry/alpha/action/migrate_test.go
  staging/operator-registry/alpha/action/migrations/000_bundle_object_to_csv_metadata.go
  staging/operator-registry/alpha/action/migrations/migrations.go
  staging/operator-registry/alpha/action/migrations/migrations_test.go
  staging/operator-registry/alpha/action/render.go
  staging/operator-registry/alpha/action/render_test.go
  staging/operator-registry/alpha/template/basic/basic.go
  staging/operator-registry/alpha/template/semver/semver.go
  staging/operator-registry/alpha/template/semver/types.go
  staging/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  staging/operator-registry/cmd/opm/alpha/template/basic.go
  staging/operator-registry/cmd/opm/alpha/template/semver.go
  staging/operator-registry/cmd/opm/migrate/cmd.go
  staging/operator-registry/cmd/opm/render/cmd.go
  staging/operator-registry/pkg/api/api_to_model.go
  staging/operator-registry/pkg/api/conversion_test.go
  staging/operator-registry/pkg/registry/registry_to_model.go
  staging/operator-registry/pkg/registry/registry_to_model_test.go
  staging/operator-registry/pkg/server/server_test.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrate.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrations/000_bundle_object_to_csv_metadata.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrations/migrations.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/render.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/basic/basic.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/types.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/basic.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/semver.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/migrate/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/render/cmd.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/api_to_model.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#856 NO-ISSUE: Manually Synchronize From Upstream Repositories (Sept. 6)
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, jira/valid-reference

#855 OCPBUGS-39574: (fix) registry pods do not come up again after node failure (#3366)
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#858 OCPBUGS-41498: [release-4.17] Fix e2e flake: upgrade CRD with deprecated version
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#860 OCPBUGS-41549: [4.17] adds paginating lister for evaluating CRs' upgrade fitness versus new CRDs.
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#836 [release-4.13] OCPBUGS-38254: [CARRY] perform operator apiService certificate validity checks directly
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/install/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/openshift/suite_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/suite_test.go
  staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#859 OCPBUGS-41540: [4.16] add optional schema migrations; default to olm.bundle.object instead of olm.csv.metadata (#1384)
  staging/operator-registry/alpha/action/migrate.go
  staging/operator-registry/alpha/action/migrate_test.go
  staging/operator-registry/alpha/action/migrations/000_bundle_object_to_csv_metadata.go
  staging/operator-registry/alpha/action/migrations/migrations.go
  staging/operator-registry/alpha/action/migrations/migrations_test.go
  staging/operator-registry/alpha/action/render.go
  staging/operator-registry/alpha/action/render_test.go
  staging/operator-registry/alpha/template/basic/basic.go
  staging/operator-registry/alpha/template/composite/builder.go
  staging/operator-registry/alpha/template/semver/semver.go
  staging/operator-registry/alpha/template/semver/types.go
  staging/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  staging/operator-registry/cmd/opm/alpha/template/basic.go
  staging/operator-registry/cmd/opm/alpha/template/semver.go
  staging/operator-registry/cmd/opm/migrate/cmd.go
  staging/operator-registry/cmd/opm/render/cmd.go
  staging/operator-registry/pkg/api/api_to_model.go
  staging/operator-registry/pkg/api/conversion_test.go
  staging/operator-registry/pkg/registry/registry_to_model.go
  staging/operator-registry/pkg/registry/registry_to_model_test.go
  staging/operator-registry/pkg/server/server_test.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrate.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrations/000_bundle_object_to_csv_metadata.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrations/migrations.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/render.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/basic/basic.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/composite/builder.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/types.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/basic.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/semver.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/migrate/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/render/cmd.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/api_to_model.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#868 OCPBUGS-41981: (fix) registry pods do not come up again after node failure (#3366)
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#869 OCPBUGS-42017: adds paginating lister for evaluating CRs' upgrade fitness versus new CRDs.
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#872 OCPBUGS-42150: (fix) registry pods do not come up again after node failure (#3366)
  go.mod
  go.sum
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/net/multi_listen.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#873 [release-4.12] OCPBUGS-42161: adds paginating lister for evaluating CRs' upgrade fitness versus new CRDs
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#874 OCPBUGS-42114: add optional schema migrations; default to olm.bundle.object instead of olm.csv.metadata
  staging/operator-registry/alpha/action/migrate.go
  staging/operator-registry/alpha/action/migrate_test.go
  staging/operator-registry/alpha/action/migrations/000_bundle_object_to_csv_metadata.go
  staging/operator-registry/alpha/action/migrations/migrations.go
  staging/operator-registry/alpha/action/migrations/migrations_test.go
  staging/operator-registry/alpha/action/render.go
  staging/operator-registry/alpha/action/render_test.go
  staging/operator-registry/alpha/template/basic/basic.go
  staging/operator-registry/alpha/template/composite/builder.go
  staging/operator-registry/alpha/template/semver/semver.go
  staging/operator-registry/alpha/template/semver/types.go
  staging/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  staging/operator-registry/cmd/opm/alpha/template/basic.go
  staging/operator-registry/cmd/opm/alpha/template/semver.go
  staging/operator-registry/cmd/opm/migrate/cmd.go
  staging/operator-registry/cmd/opm/render/cmd.go
  staging/operator-registry/pkg/api/api_to_model.go
  staging/operator-registry/pkg/api/conversion_test.go
  staging/operator-registry/pkg/registry/registry_to_model.go
  staging/operator-registry/pkg/registry/registry_to_model_test.go
  staging/operator-registry/pkg/server/server_test.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrate.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrations/000_bundle_object_to_csv_metadata.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/migrations/migrations.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/render.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/basic/basic.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/composite/builder.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/semver.go
  vendor/github.com/operator-framework/operator-registry/alpha/template/semver/types.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/render-graph/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/basic.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/template/semver.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/migrate/cmd.go
  vendor/github.com/operator-framework/operator-registry/cmd/opm/render/cmd.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/api_to_model.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#875 OCPBUGS-38610: (fix) Resolver: list CatSrc using client, instead of referring to registry-server cache (#3349)
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
