Repository openshift/operator-framework-olm, pull requests merged in 2024-01, with the labels that each got.

#647 OCPBUGS-22538: bump otelhttp to 44.0 for api
  go.mod
  go.sum
  staging/api/go.mod
  staging/api/go.sum
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#664 OCPBUGS-27435: OCPBUGS-25989: operators/olm: filter RBAC lists by namespace
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/requirements.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/requirements.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#665 [release-4.14] OCPBUGS-27485: [CARRY] SSC RBAC
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  scripts/generate_crds_manifests.sh
  scripts/olm-service.patch.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_01-olm-operator.serviceaccount.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#670 [release-4.15] OCPBUGS-25798: Fix snapshot failure, backport e2es
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
