Repository openshift/operator-framework-olm, pull requests merged in 2024-04, with the labels that each got.

#726 OCPBUGS-31651: [release-4.15] Correctly detect catalog image ID for extractContent catalog pods
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#728 OCPBUGS-31842: copy-content: delete destination dirs before copying (#3197)
  staging/operator-lifecycle-manager/cmd/copy-content/main.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/copy-content/main.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#733 OCPBUGS-28230: enforce termination message policy on all platform pods
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#736 OCPBUGS-32311: [release-4.15]: Update if AlreadyExists
  staging/operator-lifecycle-manager/pkg/api/wrappers/deployment_install_client.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/install/certresources_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/controller/operators/operatorcondition_controller.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/apiservice.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrole.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/configmap.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/customresources.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/deployment.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/operatorclientmocks/mock_client.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/role.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/rolebinding.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/secret.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/service.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/wrappers/deployment_install_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/operatorcondition_controller.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/apiservice.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrole.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/customresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/deployment.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/role.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/rolebinding.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/secret.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/service.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#703 AUTH-482: set required-scc for openshift workloads
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  microshift-manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_07-olm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  pkg/manifests/csv.yaml
  scripts/catalog-deployment.patch.yaml
  scripts/generate_crds_manifests.sh
  scripts/olm-deployment.patch.yaml
  scripts/packageserver-deployment.patch.yaml
Labels: approved, lgtm, jira/valid-reference
