Repository openshift/operator-framework-olm, pull requests merged in 2024-02, with the labels that each got.

#684 OCPBUGS-29116: [release-4.15]: Clear (existing) error cond from Subscription, once error resolved
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#675 [release-4.14] OCPBUGS-27314: Don't sync namespaces that have no subscriptions
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#681 NO-ISSUE: Remove ncdc from OWNERS #68
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, jira/valid-reference

#683 OCPBUGS-29083: * olm,catalog: only validate the resources we label
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/ownerrefs_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/labeller/filters.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
  staging/operator-lifecycle-manager/pkg/lib/testobj/runtime.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/labeller/filters.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#694 NO-ISSUE: [release-4.15] Backport flaky CRD upgrade block e2e test fix
  staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#674 NO-ISSUE: [release-4.14] Backport e2e fixes to 4.14
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/packagemanifest_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/user_defined_sa_test.go
  staging/operator-lifecycle-manager/test/e2e/util.go
  staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#689 [release-4.14] OCPBUGS-29194: Retry failing unpack jobs
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundlefakes/fake_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscriptions_test.go
  staging/operator-lifecycle-manager/test/e2e/fbc_provider.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#686 OCPBUGS-29192: [release-4.14]: Clear (existing) error cond from Subscription, once error resolved
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
