Repository openshift/operator-framework-olm, pull requests merged in 2024-08, with the labels that each got.

#831 OCPBUGS-36500: remove cvo hypershift profile annotation from psm-operator manifests
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-olmconfigs.crd.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-operators.crd.yaml
  manifests/0000_50_olm_00-packageserver.pdb.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-olmconfig.yaml
  manifests/0000_50_olm_02-services.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.service.yaml
  manifests/0000_50_olm_06-psm-operator.servicemonitor.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_11-olm-operators.configmap.removed.yaml
  manifests/0000_50_olm_12-olm-operators.catalogsource.removed.yaml
  manifests/0000_50_olm_13-operatorgroup-default.yaml
  manifests/0000_50_olm_14-packageserver.subscription.removed.yaml
  manifests/0000_50_olm_15-csv-viewer.rbac.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  manifests/0000_90_olm_00-service-monitor.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  microshift-manifests/0000_50_olm_00-catalogsources.crd.yaml
  microshift-manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  microshift-manifests/0000_50_olm_00-installplans.crd.yaml
  microshift-manifests/0000_50_olm_00-namespace.yaml
  microshift-manifests/0000_50_olm_00-olmconfigs.crd.yaml
  microshift-manifests/0000_50_olm_00-operatorconditions.crd.yaml
  microshift-manifests/0000_50_olm_00-operatorgroups.crd.yaml
  microshift-manifests/0000_50_olm_00-operators.crd.yaml
  microshift-manifests/0000_50_olm_00-packageserver.pdb.yaml
  microshift-manifests/0000_50_olm_00-subscriptions.crd.yaml
  microshift-manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  microshift-manifests/0000_50_olm_02-olmconfig.yaml
  microshift-manifests/0000_50_olm_02-services.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.service.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.servicemonitor.yaml
  microshift-manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  microshift-manifests/0000_50_olm_11-olm-operators.configmap.removed.yaml
  microshift-manifests/0000_50_olm_12-olm-operators.catalogsource.removed.yaml
  microshift-manifests/0000_50_olm_13-operatorgroup-default.yaml
  microshift-manifests/0000_50_olm_14-packageserver.subscription.removed.yaml
  microshift-manifests/0000_50_olm_15-csv-viewer.rbac.yaml
  microshift-manifests/0000_50_olm_99-operatorstatus.yaml
  microshift-manifests/0000_90_olm_00-service-monitor.yaml
  microshift-manifests/0000_90_olm_01-prometheus-rule.yaml
  scripts/generate_crds_manifests.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#832 NO-ISSUE: Update junit report file name to show spec results on Test Grid
  Makefile
Labels: approved, lgtm, jira/valid-reference

#833 OCPBUGS-38129: [release-4.16] Update junit report file name to show spec results on Test Grid
  Makefile
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#838 OCPBUGS-38290: [release-4.16] (fix) Resolver: list CatSrc using client, instead of referring to registry-server cache
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#842 [release-4.14] OCPBUGS-38544: (fix) Resolver: list CatSrc using client, instead of referring to registry-server cache (#3349)
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#843 [release-4.13] OCPBUGS-38608: (fix) Resolver: list CatSrc using client, instead of referring to registry-server cache (#3349)
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
