Repository openshift/operator-framework-olm, pull requests merged in 2024-07, with the labels that each got.

#804 OCPBUGS-35970: don't erase the filesystem from the base tools image
  operator-framework-tools.Dockerfile
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#788 [release-4.16] OCPBUGS-34979: Updates default security context behavior for catalog source pods
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  microshift-manifests/0000_50_olm_00-catalogsources.crd.yaml
  staging/api/crds/operators.coreos.com_catalogsources.yaml
  staging/api/crds/zz_defs.go
  staging/api/pkg/operators/v1alpha1/catalogsource_types.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_catalogsources.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#812 OCPBUGS-35970: add io.openshift.release.operator label to image
  operator-framework-tools.Dockerfile
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#799 [release-4.16] OCPBUGS-36137: fix sorting unpack jobs
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#793 [release-4.16] OCPBUGS-25019: fix xplat compile for of-tools image; hide utest files from git; use rhel8 art builder image
  .gitignore
  operator-framework-tools.Dockerfile
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#809 [release-4.16] OCPBUGS-36450: Can't install operator on 4.15 after uninstalling it on a prior version
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#819 [release-4.15] OCPBUGS-36813: [CARRY] perform operator apiService certificate validity checks directly
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/install/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#810 [release-4.15] OCPBUGS-36451: Can't install operator on 4.15 after uninstalling it on a prior version
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#822 [release-4.16] OCPBUGS-37018: Bump github.com/containers/image/v5
  go.mod
  go.sum
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-registry/go.mod
  staging/operator-registry/go.sum
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/github.com/containers/image/v5/docker/docker_image.go
  vendor/github.com/containers/image/v5/docker/docker_image_dest.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/docker/docker_transport.go
  vendor/github.com/containers/image/v5/docker/registries_d.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#811 [release-4.14] OCPBUGS-36452: Can't install operator on 4.15 after uninstalling it on a prior version
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#814 OCPBUGS-37559: [release-4.16] Update e2e config and backport list of flakes
  Makefile
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#828 [release-4.15] OCPBUGS-37554: Set required-scc for openshift workloads
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  microshift-manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_07-olm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  pkg/manifests/csv.yaml
  scripts/catalog-deployment.patch.yaml
  scripts/generate_crds_manifests.sh
  scripts/olm-deployment.patch.yaml
  scripts/packageserver-deployment.patch.yaml
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#829 OCPBUGS-37677: [release-4.15] Update e2e config and backport list of flakes
  Makefile
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference
