Repository openshift/operator-framework-olm, pull requests merged in 2024-06, with the labels that each got.

#767 [release-4.16] OCPBUGS-35219: Unblock CI
  Makefile
  staging/operator-lifecycle-manager/.github/workflows/e2e-tests.yml
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/deploy/chart/values.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
  staging/operator-lifecycle-manager/pkg/lib/filemonitor/monitor/loaded.crt
  staging/operator-lifecycle-manager/pkg/lib/filemonitor/monitor/loaded.key
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_exclusion_test.go
  staging/operator-lifecycle-manager/test/e2e/data/catalog.new.yaml
  staging/operator-lifecycle-manager/test/e2e/data/catalog.old.yaml
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog_test.go
  staging/operator-lifecycle-manager/test/e2e/skopeo.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/testdata/bad-csv/bad-csv.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.1.0/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.2.0-invalid-csv/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.2.0-invalid-deployment/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.2.1-invalid-csv/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.3.0-replaces-invalid-csv/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.3.0-replaces-invalid-deployment/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.3.0-skip-range/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.3.0-skips/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/magiccatalog/fbc_catalog.json
  staging/operator-lifecycle-manager/test/e2e/testdata/magiccatalog/fbc_initial.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/magiccatalog/fbc_updated.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.1.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.2.0-deprecations.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.2.0-invalid-csv.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.2.0-non-existent-tag.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.2.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.3.0-deprecations.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.3.0.yaml
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#768 [release-4.15] OCPBUGS-35229: Unblock CI
  Makefile
  go.mod
  staging/operator-lifecycle-manager/.github/workflows/e2e-tests.yml
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/deploy/chart/values.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
  staging/operator-lifecycle-manager/pkg/lib/filemonitor/monitor/loaded.crt
  staging/operator-lifecycle-manager/pkg/lib/filemonitor/monitor/loaded.key
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/catalog_exclusion_test.go
  staging/operator-lifecycle-manager/test/e2e/data/catalog.new.yaml
  staging/operator-lifecycle-manager/test/e2e/data/catalog.old.yaml
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog_test.go
  staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/testdata/bad-csv/bad-csv.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.1.0/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.2.0-invalid-csv/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.2.0-invalid-deployment/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.2.1-invalid-csv/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.3.0-replaces-invalid-csv/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.3.0-replaces-invalid-deployment/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.3.0-skip-range/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/fail-forward/v0.3.0-skips/packagemanifest.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/magiccatalog/fbc_catalog.json
  staging/operator-lifecycle-manager/test/e2e/testdata/magiccatalog/fbc_initial.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/magiccatalog/fbc_updated.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.1.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.2.0-deprecations.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.2.0-invalid-csv.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.2.0-non-existent-tag.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.2.0.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.3.0-deprecations.yaml
  staging/operator-lifecycle-manager/test/e2e/testdata/subscription/example-operator.v0.3.0.yaml
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#772 [release-4.13] OCPBUGS-35241: Unblock CI
  Makefile
  staging/operator-lifecycle-manager/.github/workflows/e2e-tests.yml
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/deploy/chart/values.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#773 [release-4.12] OCPBUGS-35242: Unblock CI
  Makefile
  staging/operator-lifecycle-manager/.github/workflows/e2e-tests.yml
  staging/operator-lifecycle-manager/Makefile
  staging/operator-lifecycle-manager/deploy/chart/values.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/test/e2e/magic_catalog.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#747 [release-4.15] OCPBUGS-31939,OCPBUGS-31940: UPSTREAM: <carry>: update golang.org/x/net for CVE-2023-45288
  go.mod
  go.sum
  staging/api/go.mod
  staging/api/go.sum
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-registry/go.mod
  staging/operator-registry/go.sum
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#787 OCPBUGS-31969,OCPBUGS-31970: UPSTREAM: <carry>: update golang.org/x/net for CVE-2023-45288
  go.mod
  go.sum
  staging/api/go.mod
  staging/api/go.sum
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-registry/go.mod
  staging/operator-registry/go.sum
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#781 OCPBUGS-35373: [release-4.16] Warn and allow CRD upgrade if validation fails but webhook is specified
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#779 OCPBUGS-35305: [release-4.15] catalog-operator: delete catalog pods stuck in Terminating state due to unreachable node
  go.mod
  go.sum
  staging/operator-lifecycle-manager/Dockerfile
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/go.sum
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#770 OPRUN-3221: 🌱 fix xplat compile for of-tools image; hide utest files from git; use rhel8 art builder image
  .gitignore
  operator-framework-tools.Dockerfile
Labels: approved, lgtm, backport-risk-assessed, jira/valid-reference

#796 NO-ISSUE: Manual Sync
  Makefile
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/install/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, jira/valid-reference

#798 [release-4.16] OCPBUGS-36138: perform operator apiService certificate validity checks directly
  staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
  staging/operator-lifecycle-manager/pkg/controller/install/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
  staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go
  staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#802 OCPBUGS-35970: switch base image
  operator-framework-tools.Dockerfile
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference
