Repository openshift/operator-framework-olm, pull requests merged in 2025-03, with the labels that each got.

#972 OCPBUGS-42526: Ensure that PSA label is latest instead of pinning versions
  manifests/0000_50_olm_00-namespace.yaml
  microshift-manifests/0000_50_olm_00-namespace.yaml
  values.yaml
Labels: approved, lgtm, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#973 NO-ISSUE: Update DOWNSTREAM owners files
  DOWNSTREAM_OWNERS
  DOWNSTREAM_OWNERS_ALIASES
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#948 [release-4.15] OCPBUGS-48662: Fix concurrent namespace resolution
  staging/operator-lifecycle-manager/cmd/olm/manager.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  staging/operator-lifecycle-manager/pkg/controller/operators/operatorconditiongenerator_controller.go
  staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go
  staging/operator-lifecycle-manager/pkg/lib/filemonitor/monitor/loaded.crt
  staging/operator-lifecycle-manager/pkg/lib/filemonitor/monitor/loaded.key
  staging/operator-lifecycle-manager/pkg/lib/index/label.go
  staging/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config_test.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  staging/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  staging/operator-lifecycle-manager/pkg/package-server/server/server.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/manager.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/operatorconditiongenerator_controller.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/index/label.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/server/server.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
