Repository openshift/operator-framework-olm, pull requests merged in 2025-01, with the labels that each got.

#936 OCPBUGS-48486: Fix concurrent namespace resolution
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  staging/operator-lifecycle-manager/pkg/lib/index/label.go
  staging/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config_test.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  staging/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  staging/operator-lifecycle-manager/pkg/package-server/server/server.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/index/label.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/server/server.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#946 [release-4.18] OCPBUGS-48660: Fix concurrent namespace resolution
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  staging/operator-lifecycle-manager/pkg/lib/index/label.go
  staging/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config_test.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  staging/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  staging/operator-lifecycle-manager/pkg/package-server/server/server.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/index/label.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/server/server.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#950 [release-4.18] OCPBUGS-48644: Fix excessive catalog source snapshots cause severe performance regression
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#944 [release-4.17] OCPBUGS-45845: Fix concurrent namespace resolution
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  staging/operator-lifecycle-manager/pkg/lib/index/label.go
  staging/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config_test.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  staging/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  staging/operator-lifecycle-manager/pkg/package-server/server/server.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/index/label.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/server/server.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#947 [release-4.16] OCPBUGS-48661: Fix concurrent namespace resolution
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  staging/operator-lifecycle-manager/pkg/lib/index/label.go
  staging/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/config_test.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  staging/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  staging/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  staging/operator-lifecycle-manager/pkg/package-server/server/server.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/state.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_nsexcemptions.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/index/label.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/kubestate/kubestate.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/resourcequeue.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/provider/registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/server/server.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#956 [release-4.17] OCPBUGS-48695: Fix excessive catalog source snapshots cause severe performance regression
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#957 [release-4.16] OCPBUGS-48696: Fix excessive catalog source snapshots cause severe performance regression
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#958 [release-4.15] OCPBUGS-48697: Fix excessive catalog source snapshots cause severe performance regression
  staging/operator-lifecycle-manager/go.mod
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  staging/operator-lifecycle-manager/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
