Repository openshift/operator-framework-olm, pull requests merged in 2025-08, with the labels that each got.

#1043 NO-ISSUE: Enable readonlyRootFilesystem by default
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_07-olm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  pkg/manifests/csv.yaml
  scripts/catalog-deployment.patch.yaml
  scripts/generate_crds_manifests.sh
  scripts/olm-deployment.patch.yaml
  scripts/packageserver-deployment.patch.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1057 NO-ISSUE: Update OWNERS to reflect current team makeup
  DOWNSTREAM_OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#1032 NO-JIRA: Remove deleted yamls
  manifests/0000_50_olm_11-olm-operators.configmap.removed.yaml
  manifests/0000_50_olm_12-olm-operators.catalogsource.removed.yaml
  manifests/0000_50_olm_14-packageserver.subscription.removed.yaml
  microshift-manifests/0000_50_olm_11-olm-operators.configmap.removed.yaml
  microshift-manifests/0000_50_olm_12-olm-operators.catalogsource.removed.yaml
  microshift-manifests/0000_50_olm_14-packageserver.subscription.removed.yaml
  scripts/generate_crds_manifests.sh
Labels: ok-to-test, approved, lgtm, jira/valid-reference
