Repository openshift/operator-framework-olm, pull requests merged in 2025-05, with the labels that each got.

#992 [release-4.18] OCPBUGS-51245,OCPBUGS-51227,OCPBUGS-51225: pin go-jose/v4@v4.0.5 (#3550)
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#998 OCPBUGS-51226,OCPBUGS-51228,OCPBUGS-51246: (vendor) pin go-jose/v4@v4.0.5
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/crypter.go
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/go-jose/go-jose/v4/opaque.go
  vendor/github.com/go-jose/go-jose/v4/signing.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#999 OCPBUGS-56034: fix(olm): improve error logging for missing olm.managed label (#3558)
  staging/operator-lifecycle-manager/pkg/controller/operators/labeller/filters.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/labeller/filters.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1008 OPRUN-3923,OPRUN-3906,OPRUN-3903,OPRUN-3926: Add NetworkPolicy support to OLMv0 components
  manifests/0000_50_olm_01-networkpolicies.yaml
  manifests/0000_50_olm_02-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_03-olmconfig.yaml
  manifests/0000_50_olm_03-services.yaml
  manifests/0000_50_olm_06-psm-operator.networkpolicy.yaml
  manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  manifests/0000_50_olm_07-collect-profiles.networkpolicy.yaml
  microshift-manifests/0000_50_olm_01-networkpolicies.yaml
  microshift-manifests/0000_50_olm_02-olm-operator.serviceaccount.yaml
  microshift-manifests/0000_50_olm_03-olmconfig.yaml
  microshift-manifests/0000_50_olm_03-services.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.networkpolicy.yaml
  microshift-manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
  microshift-manifests/0000_50_olm_07-collect-profiles.networkpolicy.yaml
  microshift-manifests/kustomization.yaml
  scripts/generate_crds_manifests.sh
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_01-networkpolicies.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_02-olm-operator.serviceaccount.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_03-olmconfig.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_03-services.yaml
  staging/operator-lifecycle-manager/deploy/chart/values.yaml
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
  staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/helpers.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/networkpolicy.go
  staging/operator-lifecycle-manager/pkg/lib/operatorclient/operatorclientmocks/mock_client.go
  staging/operator-lifecycle-manager/pkg/lib/operatorlister/lister.go
  staging/operator-lifecycle-manager/pkg/lib/operatorlister/networkpolicy.go
  staging/operator-lifecycle-manager/pkg/lib/operatorlister/operatorlisterfakes/fake_operator_lister.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util.go
  values.yaml
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/helpers.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/networkpolicy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorlister/lister.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorlister/networkpolicy.go
Labels: approved, lgtm, jira/valid-reference
