Repository openshift/operator-framework-olm, pull requests merged in 2025-09, with the labels that each got.

#1077 OCPBUGS-61362: [4.20] e2e stability fixes
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/util.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1079 OCPBUGS-61363: [4.19] e2e stability fixes
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1080 OCPBUGS-61364: [4.18] e2e stability fixes
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1081 OCPBUGS-57092: [release-4.17] e2e stability fixes
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1083 OCPBUGS-61388: [4.16] e2e stability fixes
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1084 OCPBUGS-61389: [4.15] e2e stability fixes
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1085 OCPBUGS-61390: [4.14] e2e stability fixes
  staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1086 OCPBUGS-61391: [4.13] e2e stability fixes
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1087 OCPBUGS-61392: [4.12] e2e stability fixes
  staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
  staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
  staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1052 OCPBUGS-61469: [release-4.14] Add NetworkPolicy as a supported kind
  manifests/0000_50_olm_01-networkpolicies.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_01-networkpolicies.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go
  staging/operator-registry/pkg/lib/bundle/supported_resources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/bundle/supported_resources.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1054 OCPBUGS-61471: [release-4.12] Add NetworkPolicy as a supported kind
  manifests/0000_50_olm_01-networkpolicies.yaml
  staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_01-networkpolicies.yaml
  staging/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go
  staging/operator-registry/pkg/lib/bundle/supported_resources.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/bundle/supported_resources.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1102 [release-4.16] OCPBUGS-58881: operatorgroup: ensure clusterroleselectors in clusterrole aggregation rules are sorted
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
  staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup_test.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
Labels: approved, lgtm, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference, verified

#1104 NO-ISSUE: set package-server-manager as default container
  manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  manifests/0000_50_olm_06-psm-operator.deployment.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
  microshift-manifests/0000_50_olm_06-psm-operator.deployment.yaml
  scripts/generate_crds_manifests.sh
Labels: ok-to-test, approved, lgtm, qe-approved, jira/valid-reference, verified

#1117 OCPQE-29415:correct suite name
  tests-extension/cmd/main.go
Labels: approved, lgtm, jira/valid-reference, verified
